### PR TITLE
Fix auto restart of pending Auto Upload entries

### LINKED ISSUE #2055: Photos are stuck in the queue (instant upload)
### Actual behaviour
App is set to "upload only with WiFi connection.
Turn off WLAN
make photo (Nextcloud app add the photo in the queue)
Turn on WLAN...
Nextcloud APP never starts the upload. 

### Expected behaviour
Nextcloud App should upload if the WiFi is accessible
 
### Steps to reproduce
see "### Actual behaviour"

### Environment data
Android version:
7.0

Device model: 
S8 Samsung

Stock or customized system:
Stock
Nextcloud app version:
3.0.0 RC2
Nextcloud server version:
Nextcloud 12.0.5

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

@AndyScherzinger test pls.

Fixes #2055

### CODE REVIEW

**Comment by mario** [comment]
cc @AndyScherzinger ^_^

**Comment by AndyScherzinger** [comment]
👍 WOOHOO 🎉 Great job @mario -> Works perfectly fine for my on OP3T Android 8, for already waiting files and also for wifi-off, photos taken, wifi-on. Instantly triggers the auto upload of the images. Kudos 👍 

pinging @tobiasKaminsky for second review/test

**Comment by mario** [comment]
@tobiasKaminsky this needs to be merged for 3.0.

File: src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java [hunk 1]
```diff
@@ -412,8 +363,16 @@ private OCUpload createOCUploadFromCursor(Cursor c) {
      * Get all failed uploads.
      */
     public OCUpload[] getFailedUploads() {
-        return getUploads(ProviderTableMeta.UPLOADS_STATUS + "== ?", new String[]
-                          {String.valueOf(UploadStatus.UPLOAD_FAILED.value)});
+        return getUploads(ProviderTableMeta.UPLOADS_STATUS + "== ?" +
+                " OR " + ProviderTableMeta.UPLOADS_LAST_RESULT +
+                        "==" + UploadResult.DELAYED_FOR_WIFI.getValue() +
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java]: This will list an upload that is waiting for wifi as failed upload?
If "retry failed" is clicked, this will also retry it then. Is this intended? 
(same for the other delayed reasons)

**Comment by tobiasKaminsky** [comment]
@mario Just one question.
Can you also review the other pending PRs?
Then I can do RC3 tomorrow, which fits perfectly as NC13 is delayed to next tuesday.

File: src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java (hunk 1 above)
Comment (mario) [reply src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java]: Intended, yes. It will only retry it if conditions are met anyway.

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java]: I remember some user complaining that pending uploads are retried even if the conditions are not met. This would then be the same here, or?

As far as I understand this retries all failed/pending uploads and as there might be a network change inbetween, it will also retry and start those uploads that are e.g. waiting for wifi, just like Andy tested it:
- wifi off
- take picture
- upload is waiting_for_wifi
- wifi on
- get all failed uploads, which then also triggers the "delayed for wifi" one

In my opinion the right way would be to trigger specifically those "delayed for wifi" on connection change, or?
(But this might not work reliable and if so, I am fine with merging)

**Comment by mario** [comment]
This is how it works already. Check retryfaileduplpads method :)

File: src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java (hunk 1 above)
Comment (mario) [reply src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java]: This is exactly how it works :) But before this PR it didn't even take almost anything into consideration for retry.

**Comment by tobiasKaminsky** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Thanks for clarification
