### PR TITLE
Fix back arrow appearing as hamburger icon

### LINKED ISSUE #11679: Back navigation button missing when opening pdf
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. provide pdf document on nextcloud server
2. ensure that no local copy exists
3. open document (will be synced and promptly displayed)
4. navigate back

### Expected behaviour

Upon back navigation the file list (or previous activity) should be displayed.

### Actual behaviour

Upon navigation an empty *Activity* tab is shown, where the back navigation button (←) in the upper left corner has been replaced by a hamburger menu.

Returning to the main file list is, however, still possible via button / swipe navigation.

When opening the now present left-hand menu, it is possible to navigate to settings and back again. Now the toolbar from the pdf view is retained and not replaced by the search bar.

### Android version

13

### Device brand and model

OnePlus 6T

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

3.24.1

### Nextcloud server version

26.0.1

### Using a reverse proxy?

No

### Android logs

_No response_

### Server error logs

_No response_

### Additional information

Custom OS: LineageOS 20.0

### PR DESCRIPTION
**Pull request by ZetaTom**
This fixes an issue where the back navigation icon (←) appeared as a hamburger menu.

fixes #11679

---

- [ ] Tests written, or not not needed

### CODE REVIEW

File: app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java [hunk 1]
```diff
@@ -1519,7 +1519,7 @@ protected void setTitle() {
                     setTitle(R.string.drawer_item_shared);
                     break;
                 default:
-                    setTitle(themeUtils.getDefaultDisplayNameForRootFolder(getContext()));
+                    setTitle(themeUtils.getDefaultDisplayNameForRootFolder(getContext()), false);
```
Comment (surinder-tsys) [inline app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java:1522]: Opening the app will shows the back button instead of hamburger menu due to passing "false" value.

Comment (ZetaTom) [reply app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java:1522]: Could you kindly specify the conditions under which the icon is displayed incorrectly, when opening the app?

Comment (surinder-tsys) [reply app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java:1522]: My bad... I missed some code while applying changes. Its working as expected.

**Comment by surinder-tsys** [comment]
As per MC customization we always use **defaultToolbar** instead of **searchToolbar** due to which we are seeing the back arrow during the app launch. 
I will handle this behaviour in our customization.

**Review by surinder-tsys — APPROVED** [review]
