### PR TITLE
Correctly parse share api

### LINKED ISSUE #8072: App crashed by setting password on OnePlus7T
### Steps to reproduce
1.  Open Android App
2.  Move to Folder. Folder has name  "24.02.2021" 
3.  Press on sharing button, press on "Share Link" - Sharing Link is generated - everything works as expected
4.  Press 3 Dots Menu Button </br>

5.  Choose "Set Password" </br>

6.  Confirm new Password -> App crashed </br>

### Expected behaviour
- Password will be set. App doesn't crashed

### Actual behaviour
- App crashed

### Can you reproduce this problem on https://try.nextcloud.com?
- No, because it just happen in the app.

**** CAUSE OF ERROR ****

java.lang.RuntimeException: Accessing result data after operation failed!
	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:488)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForUpdateShareOperations(ErrorMessageAdapter.java:204)
	at com.owncloud.android.utils.ErrorMessageAdapter.getMessageForResultAndOperation(ErrorMessageAdapter.java:152)
	at com.owncloud.android.utils.ErrorMessageAdapter.getErrorCauseMessage(ErrorMessageAdapter.java:79)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:384)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onRemoteOperationFinish(FileDisplayActivity.java:1704)
	at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:734)
	at com.owncloud.android.services.-$$Lambda$OperationsService$KsB1LbjHjlEBSp0h7XO24czs-OQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**** APP INFORMATION ****
ID: com.nextcloud.client
Version: 30150151
Build flavor: generic

**** DEVICE INFORMATION ****
Brand: OnePlus
Device: OnePlus7T
Model: HD1903
Id: QKQ1.190716.003
Product: OnePlus7T_EEA
Build: Oxygen-OS 10.0.16.HD65BA

**** FIRMWARE ****
SDK: 29
Release: 10
Incremental: 2101282100
Android-Security-Patch-Level: 2021-02-01
Google Play-Systemupdate: 2021-02-01

Nextcloud server version: 20.0.8

Reverse proxy: Apache

## Server configuration detail

**Operating system:** Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 8.0.23

**PHP version:** 7.4.3

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.8 - 20.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "nextcloud.devtube.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.8.1",
    "htaccess.RewriteVase": "\/",
    "overwrite.cli.url": "https:\/\/nextcloud.devtube.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**External storages:** files_external is disabled

**Encryption:** no

**User-backends:** 
 * OC\User\Database

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #8072 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

File: src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java [hunk 1]
```diff
@@ -166,22 +166,23 @@ private static String getMessageForResultAndOperation(
         return message;
     }
 
-    private static String getMessageForSynchronizeFolderOperation(
-            RemoteOperationResult result,
-            SynchronizeFolderOperation operation,
-            Resources res
-    ) {
+    private static @Nullable
+    String getMessageForSynchronizeFolderOperation(
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java:170]: should be single line, no?

File: src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java [hunk 2]
```diff
@@ -166,22 +166,23 @@ private static String getMessageForResultAndOperation(
...
+                new File(operation.getFolderPath()).getName()
+                                );
         }
-        return
-                null;
+        return null;
     }
 
-    private static String getMessageForMoveFileOperation(RemoteOperationResult result, Resources res) {
+    private static @Nullable
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java:184]: same here I guess?

**Review by AndyScherzinger — APPROVED** [review]
