### PR TITLE
Themes header: plain background color and logo, if available

### LINKED ISSUE #7746: Logo is not changed in the Android application
### Steps to reproduce
When I set the custom logo, in the web application it is changed correctly, but in the Android application the default Nextcloud logo is displayed.

image
image

I have installed imagick to be able to use SVG images, but it does not work either.

Is it possible to change the logo displayed in the Android application? The colors do change, but the logo does not.

### Expected behaviour
The logo should also be changed in the Android application.

### Actual behaviour
The logo is not changed in the Android application.

### Environment data
Android version: 10

Device model: Xiaomi MI8

Stock or customized system: Stock

Nextcloud App version: 3.14.1
Nextcloud Server version: 20.0.4

Reverse proxy: nginx

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #7746 

 

@jancborchardt @AndyScherzinger just showing the logo feels very empty…

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
So what about showing
The Logo centered in a square area with the name to the right as text?

**Comment by borjapazr** [comment]
> Fix #7746
> 
>  
> 
> @jancborchardt @AndyScherzinger just showing the logo feels very empty…
> 
> Signed-off-by: tobiasKaminsky [tobias@kaminsky.me](mailto:tobias@kaminsky.me)
> 
> ### Testing
> Writing tests is very important. Please try to write some tests for your PR.
> If you need help, please do not hesitate to ask in this PR for help.
> 
> [unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
> [instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
> [UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)
> 
> * [ ]  Tests written, or not not needed

What image size should be used? If the web logo is used, the size is usually square, which will not take full advantage of the space in the Android application. The letters (Nextcloud) part of the default logo would be empty.

**Comment by szaimen** [comment]
> The letters (Nextcloud) part of the default logo would be empty.

Maybe you could instead use the name that is set in the theming app if it is configured?

I am talking about the string that you get when running the following command:
`occ config:app:get theming name`

**Comment by tobiasKaminsky** [comment]
> The Logo centered in a square area with the name to the right as text?

Nice idea!

**Comment by tobiasKaminsky** [comment]
> > The Logo centered in a square area with the name to the right as text?
> 
> Nice idea!

How do we want to do it?
We do not know how long server name is.

Maybe like this:
- if there is a text, use 1/3 for squared logo, rest for name
- if there is no text, use fixed height for logo (in case it is not square)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky yeah, it's pretty much 2 layouts 
* logo+text: 1/3 for square image + text (single line center-ellipsized)
* logo-no text: full-width image, centered (basically as it is today)

What I can't say is what a non-themed server would reply today 8where would show the Nc logo wiith its graphical text)

**Comment by tobiasKaminsky** [comment]
> What I can't say is what a non-themed server would reply today 8where would show the Nc logo wiith its graphical text)

That is "easy", as then there is no logo available, neither custom image nor server name is shown.
So it defaults to our normal logo.

File: src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java [hunk 1]
```diff
@@ -269,11 +272,61 @@ private void setupQuotaElement() {
...
+        ImageView imageHeader = mNavigationViewHeader.findViewById(R.id.drawer_header_logo);
+        imageHeader.setImageDrawable(drawable);
+        imageHeader.setScaleType(ImageView.ScaleType.FIT_START);
+        imageHeader.setAdjustViewBounds(true);
+
+        imageHeader.setMaxWidth(DisplayUtils.convertDpToPixel(100f, this));
+
+        LinearLayout.MarginLayoutParams params = new LinearLayout.MarginLayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,
+                                                                               LinearLayout.LayoutParams.MATCH_PARENT);
+        params.leftMargin = 20;
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java:319]: @tobiasKaminsky would have expected reading the `standard_margin` value from `dimens.xml` since that way you get a proper, density-respecting value, this way it is 20 pixel, no mater the devices dpi.

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java:319]: I tried it.
- with just replacing it by R.dimen.standard_margin (20dp) no icon and no text is shown
- with converting it to pixel via DisplayUtils.convertDpToPixel(…), there is no icon, but text is still shown.

What do you think about my approach?

Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java]: @tobiasKaminsky any server(-connection) where I could test this?

**Review by AndyScherzinger — APPROVED** [review]

**Comment by szaimen** [comment]
How to test this if it is working?
I've installed this QA version: https://github.com/nextcloud/android/pull/7794#issuecomment-778999779
and logged in on my NC 20.0.7 instance with custom logo and server name but it still shows the default name (Nextcloud and also the default logo, as far as I can see) in the hamburger menu. Is something else needed to get this working?

**Comment by tobiasKaminsky** [comment]
>  Is something else needed to get this working?

No, this is enough.
It might be that you have to refresh root folder, close app and re-open it.
(this is due that drawer, and thus icon/name, is only created on app startup)

**Comment by szaimen** [comment]
> It might be that you have to refresh root folder, close app and re-open it.

I've tried this but it still doesn't work. 
Is this maybe related to the missing imagick packet on my server or that my root folder is read only?

**Comment by tobiasKaminsky** [comment]
@szaimen 
Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by szaimen** [comment]
> Can you create us a test account and send the credentials to tobias at nextcloud dot com with a reference to this issue?

Done 👍

**Comment by tobiasKaminsky** [comment]
It seems that the app has problems when displaying a svg image (which is the default NC icon).
I only tested it with custom png/jpg images.

**Comment by szaimen** [comment]
Hm... It would be a bit strange if that would fix the issue since the favicon that I've added in the theming app is a png (if I remember correctly)...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see `LoadBitmapTask` in `PreviewIMageFragment` which has a SVG mimetype code branch for the preview image pager to handle svg vs. standard-pixel-bitmap images. So that might solve the problem while the view-typer might need to be changed to PhotoView (not sure about that)

**Comment by tobiasKaminsky** [comment]
I found a way so that Glide loads SVG in case if bitmap fails, but this now means that 
- glide loads image via network
- tries bitmap
- fails
- loads image via network again
- shows svg

We do not know in advance if it is a SVG or bitmap.
Furthermore on next start Glide would try again bitmap, then fails, then loads SVG from cache.
A solution for this would be to store bitmap or svg in db, so that we know what to use.

**Comment by tobiasKaminsky** [comment]
@szaimen can you test latest APK?

**Comment by szaimen** [comment]
> @szaimen can you test latest APK?

It works for me now, thanks! :)

**Comment by tobiasKaminsky** [comment]
> @szaimen can you test latest APK?

After the test, I'll do code clean up, rebase, etc.

**Comment by szaimen** [comment]
🎉
