### PR TITLE
Fix NPE in virtuals

### LINKED ISSUE #1442: GPlay:   java.lang.NullPointerException - com.owncloud.android.utils.MimeTypeUtil.isImage
Since 2.0.0RC4 (reported for the first time) - Imho not related to RC4 but 2.0.0 in general (search+preview view?)
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2720)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2781)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1508)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:6274)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: 
  at com.owncloud.android.utils.MimeTypeUtil.isImage (MimeTypeUtil.java:257)
  at com.owncloud.android.datamodel.FileDataStorageManager.getVirtualFolderContent (FileDataStorageManager.java:2145)
  at com.owncloud.android.ui.preview.PreviewImagePagerAdapter.<init> (PreviewImagePagerAdapter.java:116)
  at com.owncloud.android.ui.preview.PreviewImageActivity.initViewPager (PreviewImageActivity.java:139)
  at com.owncloud.android.ui.preview.PreviewImageActivity.onAccountSet (PreviewImageActivity.java:482)
  at com.owncloud.android.ui.activity.BaseActivity.onStart (BaseActivity.java:192)
  at com.owncloud.android.ui.activity.DrawerActivity.onStart (DrawerActivity.java:1273)
  at com.owncloud.android.ui.activity.FileActivity.onStart (FileActivity.java:188)
  at com.owncloud.android.ui.preview.PreviewImageActivity.onStart (PreviewImageActivity.java:173)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1249)
  at android.app.Activity.performStart (Activity.java:6737)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2683)
```

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
fix #1442

- use nullable
- only add non-null object to list

I do not understand why there can be a null while reading from database, but as createFileInstanceFromVirtual() can return null, it is always safer to handle this properly.

### CODE REVIEW

File: src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java [hunk 1]
```diff
@@ -2148,16 +2150,18 @@ public void saveVirtual(VirtualFolderType type, OCFile file) {
...
             } while (c.moveToNext());
             c.close();
         }
 
         if (onlyImages) {
-            OCFile current = null;
             Vector<OCFile> temp = new Vector<>();
             for (int i=0; i < ocFiles.size(); i++) {
-                current = ocFiles.get(i);
+                OCFile current = ocFiles.get(i);
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java]: Why did you change this? Imho this leads to instantiation costs per loop iteration while the former code would have simply replaced the reference which should be cheaper, I think.

**Comment by AndyScherzinger** [comment]
Just one minor comment + branch is out-of-date for master

File: src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java (hunk 1 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java]: As far as I read this should be no real (experienced) difference:
http://drmirror.net/2013/06/06/object-creation/

Creating a list view (instead of recycler view) out of these virtuals will take way longer than this loop ;-)

Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java]: 👍

**Comment by AndyScherzinger** [comment]
👍 fine by me

File: src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java (hunk 1 above)
Comment (mario) [reply src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java]: I would personally prefer a reference too and then I can approve.

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍 fine by me
