### PR TITLE
Check for right media type in auto upload

### LINKED ISSUE #12910: Autouploaded Videos Showing Up in Photos Directory
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Set up autoupload with separate profiles for photos vs videos using the same monitored camera directory but autouploading to two separate photo vs video remote directories.
2. Take a video.
3. Notice that the video file appears in both the photo and video remote directories as a duplicate file.

### Expected behaviour

Android client should respect the photo vs video profiles and only upload to their respective remote directories.

### Actual behaviour

Video file is duplicated on the Nextcloud remote in both the photo and video directories.

### Android version

13

### Device brand and model

OnePlus

### Stock or custom OS?

Stock

### Nextcloud android app version

3.28.2

### Nextcloud server version

28.0.4

### Using a reverse proxy?

Yes

### Android logs

_No response_

### Server error logs

_No response_

### Additional information

Looking back through my directories, this appears to have started within the past month (April). I don't take that many videos so it's conceivable that this began in the middle of March (the last timepoint I have where I took a video and it wasn't duplicated), but this does seem like a net new change.

Interestingly, it seems like others have complained of the opposite finding the separate profiles unintuitive (see Issue #12585 and Issue #12347). Perhaps changes found their way into the main release? If so, that would be particularly unfortunate since this reflects a change in longstanding autoupload behavior and since we currently lack the ability to suppress (or select) upload based on filetype, there is no available workaround to keep videos and photos in separate directories.

### LINKED ISSUE #13035: Only pictures are enabled but videos also auto-synced
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Enable sync of pictures only
2. Make a video in this directory
3. Let the auto sync function sync the files.

### Expected behaviour

If the video sync function is not enabled, then videos shall not be synced.

### Actual behaviour

If the video sync function is not enabled, then videos are synced together with pictures.

### Android version

14

### Device brand and model

Samsung A54

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

25.0.13

### Using a reverse proxy?

No

### Android logs

_No response_

### Server error logs

_No response_

### Additional information

_No response_

### LINKED ISSUE #13087: Auto Upload is Not keeping videos and pics Separate like before.
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Auto Upload

### Expected behaviour

I have 2 folders for camera roll one for pics and one for videos. Auto upload should only put videos in video folder and pics in pic folder.

### Actual behaviour

The video folder is only videos so i would say it is working fine. The picture folder is getting my pics but also putting duplicates of videos in it.

### Android version

14

### Device brand and model

Galaxy S22 Ultra

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

Nextcloud Hub 8 (29.0.1)

### Using a reverse proxy?

Yes

### Android logs

_No response_

### Server error logs

_No response_

### Additional information

The folders used to stay separate. When i go to auto upload setting in android it shows 2 camera rolls one for pics and one for videos. So i made separate folders to keep videos separate from pics. i deleted all the videos in my pics folder and now videos in video folders wont open. :(

### PR DESCRIPTION
**Pull request by JonasMayerDev**
Fixes #13087, Fixes #13035, Fixes #12910.

To test this PR, have images and videos in the same folder, activate auto upload for videos OR images and put a new file of the opposite type in the folder. Without this PR it uploads the file regardless. With that PR it first checks if it is the correct type and then uploads.

Master -> Image gets upload even though only video folder is activated

[Screen_recording_20240711_192320.webm](https://github.com/nextcloud/android/assets/43114340/555b224d-45cc-4bb7-b07d-7f99e1c62404)

PR -> No images only videos get upload when only video folder is activated

[WithPRDownscaled.webm](https://github.com/nextcloud/android/assets/43114340/d7cfcb4b-a5ea-46b5-9610-5ab3388766ce)

- [X] Tests written, or not not needed

### CODE REVIEW

**Review by alperozturk96 — CHANGES_REQUESTED** [review]
Auto upload, not uploading to the correct path after configure.


https://github.com/nextcloud/android/assets/67455295/48934779-ac41-4617-9c2d-8396accc6249

**How to Reproduce?**

1. Enable auto upload for new detected media folder
2. InstantUpload folder will be used for auto upload
3. Configure the auto upload path (e.g. MyFavFolder) for selected folder
4. Still uploading to the InstantUpload folder

File: app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java [hunk 1]
```diff
@@ -275,7 +277,11 @@ public void setExcludeHidden(boolean excludeHidden) {
     }
 
     public boolean containsFile(String filePath){
```
Comment (alperozturk96) [inline app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java:279]:
```
 public boolean containsFile(String filePath) {
        return filePath.contains(localPath);
    }

 public boolean isImageOrVideo(String filePath) {
        return (getType() == MediaFolderType.IMAGE && MimeTypeUtil.isImage(new File(filePath))) ||
                (getType() == MediaFolderType.VIDEO && MimeTypeUtil.isVideo(new File(filePath))) ||
                getType() == MediaFolderType.CUSTOM;
 }
```

It would be good to separate the logic because otherwise containsFile doing two jobs and the name of the function will mislead us.

Why getType() == MediaFolderType.CUSTOM used?

**Comment by JonasMayerDev** [comment]
> Auto upload, not uploading to the correct path after configure.
> 
>  f.mp4 
> **How to Reproduce?**
> 
> 1. Enable auto upload for new detected media folder
> 2. InstantUpload folder will be used for auto upload
> 3. Configure the auto upload path (e.g. MyFavFolder) for selected folder
> 4. Still uploading to the InstantUpload folder

I think this is also an issue on master (could you pls test). When you activate auto upload and then afterward change the directory for upload, it already uploaded the files to the wrong directory. Only new files will be uploaded to the newly specified folder. To mitigate this, you can activate and change the path of the folder using the 3 dot menu in one go.

File: app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java (hunk 1 above)
Comment (alperozturk96) [reply app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java:279]: Yes, we know that this is the case and that is exactly why we need to separate it into two functions. Otherwise, we have to give such a long explanation. 

The code should explain itself as much as possible, rather than us explaining it.

**Comment by alperozturk96** [comment]
> > Auto upload, not uploading to the correct path after configure.
> > f.mp4
> > **How to Reproduce?**
> > 
> > 1. Enable auto upload for new detected media folder
> > 2. InstantUpload folder will be used for auto upload
> > 3. Configure the auto upload path (e.g. MyFavFolder) for selected folder
> > 4. Still uploading to the InstantUpload folder
> 
> I think this is also an issue on master (could you pls test). When you activate auto upload and then afterward change the directory for upload, it already uploaded the files to the wrong directory. Only new files will be uploaded to the newly specified folder. To mitigate this, you can activate and change the path of the folder using the 3 dot menu in one go.

[Issue](https://github.com/nextcloud/android/issues/13264)

**Review by alperozturk96 — APPROVED** [review]
