### PR TITLE
Change to customeViewPager to catch error

### LINKED ISSUE #2885: App Crash if i zoom out
### Actual behaviour
App crash

### Expected behaviour
no crash
 
### Steps to reproduce
1. Open App
2. open a photo.
3. Zoom out very fast and multible times
4. APP Crash

### Environment data
Android version:
8.0.0.
Device model: 
Samsung S8
Stock or customized system:
stock
Nextcloud app version:
3.2.1
Nextcloud server version:
13.0.5

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #2885

Already confirmed to work by the reporter.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

File: src/main/java/com/owncloud/android/ui/components/CustomViewPager.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+        super(context, attrs);
+    }
+
+    @SuppressLint("ClickableViewAccessibility")
+    @Override
+    public boolean onTouchEvent(MotionEvent ev) {
+        try {
+            return super.onTouchEvent(ev);
+        } catch (IllegalArgumentException ex) {
+            Log_OC.e("CustomViewPager", "crash", ex);
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/ui/components/CustomViewPager.java]: for consistency it should be a constant named "TAG" based on the class.name

File: src/main/java/com/owncloud/android/ui/components/CustomViewPager.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        }
+        return false;
+    }
+
+    @Override
+    public boolean onInterceptTouchEvent(MotionEvent ev) {
+        try {
+            return super.onInterceptTouchEvent(ev);
+        } catch (IllegalArgumentException ex) {
+            Log_OC.e("CustomViewPager", "crash", ex);
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/ui/components/CustomViewPager.java]: see comment above

**Comment by mario** [comment]
👍
