### PR TITLE
Use localID from webdav

### LINKED ISSUE #9826: Android app fails to play media files (music) from bind-mounted folder
I cannot play music files with my nextcloud android app. I can navigate to the files and select them, but I only receive the error "Could not read the media file". The server log files show a 404 which is strange, since the files are clearly there and can actually be played without an issue using the web UI. 

The folder holding the files is mounted (mount --bind) into the user's data files section. File permissions are like those files created by nextcloud itself: user and group ownership for account "www-data", the files are group writeable and readable for everyone. The server system is a standard Ubuntu system. 

### Steps to reproduce
1. have some media files mounted into your nextcloud files section (ogg or mp3) (mount --bind)
2. scan the file system to import those files (sudo -u www-data php -f public/occ files:scan arkascha)
3. open the nextcloud app on an android device
4. navigate to the media files and select one

### Expected behaviour
The file should get played. Actually the UI clearly suggests that it is trying to play the file, there is even a play button. 

### Actual behaviour
The file is not played, I receive an error toast "Could not read the media file". 

### Can you reproduce this problem on https://try.nextcloud.com?
I cannot reproduce the same situation (mount --bind) on that system, so I cannot check this. Sorry. 

### Environment data
Android version:
LineageOS 18.1 (Android 11)

Device model: 
Oneplus 7 Pro

Stock or customized system:
Customized: LineageOS

Nextcloud app version:
Version 3.19.0, installed from google

Nextcloud server version:
Nextcloud version 23.1

Reverse proxy:
---

#### Web server error log
```
31.17.208.40 - - [13/Feb/2022:21:32:38 +0100] "POST /ocs/v2.php/apps/dav/api/v1/direct?format=json HTTP/1.1" 404 1456 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
31.17.208.40 - - [13/Feb/2022:21:32:34 +0100] "GET /index.php/apps/files/api/v1/thumbnail/256/256/Multimedia/music/All%20Saints/Black%20Coffee.mp3 HTTP/1.1" 404 822 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
31.17.208.40 - - [13/Feb/2022:21:32:51 +0100] "POST /ocs/v2.php/apps/dav/api/v1/direct?format=json HTTP/1.1" 404 1456 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.19.0"
```

#### Nextcloud log (data/nextcloud.log)
```
- - -
```

### LINKED ISSUE #10261: impossible to watch video on stream
If I try to open video stored on my nextcloud instance, th app tell me :
"Internal stream not possible" and I have this error :

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException
    at com.owncloud.android.ui.preview.PreviewVideoActivity.onStart(PreviewVideoActivity.kt:225)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
    at android.app.Activity.performStart(Activity.java:8018)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200190`
* Build flavor: `gplay`

### Device information
* Brand: `OnePlus`
* Device: `OnePlus7Pro`
* Model: `GM1917`
* Id: `RQ3A.211001.001`
* Product: `OnePlus7Pro`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `173fcd6e23`

With an older nextcloud app version (3.19.1) : no problem.
I think i didn't find this problem in existent issues

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Needs https://github.com/nextcloud/android-library/pull/651
After: 
- [x] https://github.com/nextcloud/android/pull/11098

@juliushaertl
~~we need to 
- do not use localID (which might make sense in terms of federation)
- or expose unique server id via capabilities
- or have server return localID via webdav

EDIT: using localId via webdav is the solution!

E.g. my instance has 14 chars for unique id @juliushaertl 
~~To handle this properly we need uniqe id exposed via registered capability, if this is ok for you.~~

Fixes #9826
Fixes #10261

### CODE REVIEW

File: src/main/java/com/owncloud/android/datamodel/OCFile.java [hunk 1]
```diff
@@ -552,7 +552,8 @@ public boolean isHidden() {
      * @return file fileId, unique within the instance
      */
     public String getLocalId() {
-        return getRemoteId().substring(0, 8).replaceAll("^0*", "");
+        // fileId, instanceId. instanceId is 12 chars long
+        return getRemoteId().substring(0, getRemoteId().length() - 12).replaceAll("^0*", "");
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/datamodel/OCFile.java:556]: We cannot rely on 12 long instance id!

**Comment by juliushaertl** [comment]
> EDIT: using localId via webdav is the solution!

yep sounds like the better approach :+1:

File: app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt [hunk 2]
```diff
@@ -57,7 +57,7 @@ import com.owncloud.android.db.ProviderMeta
     ],
     version = ProviderMeta.DB_VERSION,
     autoMigrations = [
-        AutoMigration(from = 65, to = 66)
+        AutoMigration(from = 65, to = 67)
```
Comment (tobiasKaminsky) [inline app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt:60]: @AlvaroBrey is this needed?
I also changed it in https://github.com/nextcloud/android/pull/8643/files#diff-ffa8f9b74f7af219ebf0927bb94e6c8d03e2b34eb9e39b1287edb1b65532a72fR38

Comment (tobiasKaminsky) [reply app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt:60]: If needed, can we combine this? Otherwise I fear we will forget it at some point.

File: app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json [hunk 3]
```diff
@@ -2,7 +2,7 @@
     "formatVersion": 1,
```
Comment (AlvaroBrey) [inline app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json:2]: Please undo changes to this file. We must _never_ change already existing schemas when changing database, that's why the new one is created. Otherwise migrations will break.

File: app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt (hunk 2 above)
Comment (AlvaroBrey) [reply app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt:60]:
```suggestion
        AutoMigration(from = 65, to = 66),
        AutoMigration(from = 66, to = 67),
```

See https://developer.android.com/training/data-storage/room/migrating-db-versions#automated. Your original change would not allow migration from 66 to 67, only from 65.

> If needed, can we combine this? Otherwise I fear we will forget it at some point.

No, we can't combine this. The migration specs need to reference static DB versions as they must be immutable in time, not a constant that will be changed later.

File: app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json (hunk 3 above)
Comment (AlvaroBrey) [reply app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json:2]: To prevent this happening, you should bump the DB version _before_ making changes to the entities.

File: app/src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java [hunk 4]
```diff
@@ -369,4 +369,11 @@ public void testOCCapability() {
 
         assertEquals(capability.getUserStatus(), newCapability.getUserStatus());
     }
+
+    @Test
+    public void saveFolder() {
+
+    }
```
Comment (AlvaroBrey) [inline app/src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java:376]: Empty test?

File: app/src/main/java/com/owncloud/android/datamodel/OCFile.java [hunk 5]
```diff
@@ -283,9 +286,13 @@ public String getRemotePath() {
         }
     }
 
+    @Override
+    public String getImageKey() {
+        return remoteId;
+    }
```
Comment (AlvaroBrey) [inline app/src/main/java/com/owncloud/android/datamodel/OCFile.java:292]: This feels out of place, the `OCFile` shouldn't have image-specific things in my opinion. I'd just use `getRemoteId` where it is needed.

**Review by AlvaroBrey — CHANGES_REQUESTED** [review]

File: app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json (hunk 3 above)
Comment (tobiasKaminsky) [reply app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json:2]: I never intentionally changed there something.
Must be done by Room…

I only changed FileEntity.

Comment (tobiasKaminsky) [reply app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json:2]: > To prevent this happening, you should bump the DB version before making changes to the entities.

That might be the keypoint! I changed Entity, started app, Room complained and then I adjusted DB version.

File: app/src/main/java/com/owncloud/android/datamodel/OCFile.java (hunk 5 above)
Comment (tobiasKaminsky) [reply app/src/main/java/com/owncloud/android/datamodel/OCFile.java:292]: This is such an old PR, that I even do not know why I did this back then.
And you are right, this feels totally off!

File: app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json (hunk 3 above)
Comment (AlvaroBrey) [reply app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json:2]: Yep, the schemes get autogenerated by Room when building. In any case, just undo the changes in 66.json and it will be good to go.

File: app/src/main/java/com/owncloud/android/datamodel/OCFile.java (hunk 5 above)
Comment (tobiasKaminsky) [reply app/src/main/java/com/owncloud/android/datamodel/OCFile.java:292]: I know remember.
We have TrashbinFile, FileVersion and OCFile, all extending form ServerFileInterface.
imageKey was then used to abstract from actual detail on ThumbnailCacheManager.

But I reverted it.

**Review by AlvaroBrey — APPROVED** [review]

**Comment by tigermick** [comment]
hi,
I have a problem here : https://github.com/nextcloud/android/issues/10261
and your Nextcloud QA release here : https://www.kaminsky.me/nc-dev/android-artifacts/8643.apk fix my problem

**Comment by AlvaroBrey** [comment]
@tobiasKaminsky is this available in all supported server versions?

Btw the new attribute in the DB will likely conflict with #11098 , so I'd rather merge that one first and solve conflicts here. Otherwise we risk losing the new attribute.

**Comment by AlvaroBrey** [comment]
@tobiasKaminsky can you see what's happening with the failing test?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky is this available in all supported server versions?

Yes, I tested it with NC16, our oldest supported version, and it returns:
```
<oc:id>00000002oc8wojm72e0q</oc:id>
<oc:fileid>2</oc:fileid>
```

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky can you see what's happening with the failing test?

Strange, I do not understand why it fails with this change.
It should have been failing either all the time, or not at all.

I will continue to check.

File: app/src/main/java/com/owncloud/android/datamodel/OCFile.java [hunk 6]
```diff
@@ -594,17 +598,14 @@ public boolean isHidden() {
...
-    @Nullable
-    public String getLocalId() {
-        if (getRemoteId() != null) {
-            return getRemoteId().substring(0, 8).replaceAll("^0*", "");
+    @SuppressFBWarnings("STT")
+    public long getLocalId() {
+        if (localId > 0) {
+            return localId;
+        } else if (remoteId != null) {
+            return Long.parseLong(remoteId.substring(0, 8).replaceAll("^0*", ""));
```
Comment (AlvaroBrey) [inline app/src/main/java/com/owncloud/android/datamodel/OCFile.java:606]: Are there servers with a remoteID shorter than 8 characters? If so we should do `substring(0, Math.min(remoteId.length(), 8)` instead of `substring(0.8)`.

Comment (tobiasKaminsky) [reply app/src/main/java/com/owncloud/android/datamodel/OCFile.java:606]: I think 8 is minimum, but there might be some with more than 8.
But as this is the old behaviour, it should not break any existing installation.

Comment (AlvaroBrey) [reply app/src/main/java/com/owncloud/android/datamodel/OCFile.java:606]: Then I don't understand why some tests failed in this pr due to a too short remoteId, but didn't fail before :\

**Review by AlvaroBrey — APPROVED** [review]

File: app/src/main/java/com/owncloud/android/datamodel/OCFile.java (hunk 6 above)
Comment (tobiasKaminsky) [reply app/src/main/java/com/owncloud/android/datamodel/OCFile.java:606]: Me neither. Which one is failing? Then I can try to debug it locally.

Comment (tobiasKaminsky) [reply app/src/main/java/com/owncloud/android/datamodel/OCFile.java:606]: https://github.com/nextcloud/android/pull/8643/commits/e1d564026f7c479b61d4404083126fbee71fbbdb#diff-940d35bacfe8905a4b0b8019f3b78e40fcb366e8b3f313dc350ecbdf671f8385R249

Here it is because of:
It tries to save file in FileDataStorageManager:460
-> and saves localId, which is then as fallback tries to substring(0,8).
In this case (on master) we just used remoteId, as is. And thus it never failed.

**Comment by AlvaroBrey** [comment]
```
/drone/src/app/src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java:656: error: cannot find symbol
--
712 | assertTrue(new DeletePrivateKeyOperation().execute(client).isSuccess());

```

**Comment by tobiasKaminsky** [comment]
Library merged, so let us merge this asap.
