### PR TITLE
Fixes #2315 and other issues

### LINKED ISSUE #2315: Wrong account displayed on notification
1. Have 2 accounts setup  in the android app, `Account A` and `Account B`
2. Switch to `Account B` in the client
3. Close the app (probably also work when it stays open but I didn't test)
4. Get a notification in `Account A`
5. Click on the notification

Now:
App is opened on `Account B`'s notification screen and you see an empty list

Expected:
App is opened on `Account A`'s notification screen and you see your notification

### PR DESCRIPTION
**Pull request by mario**
Fixes #2315

Signed-off-by: Mario Danic <mario@lovelyhq.com>

Shows real notification subject and switches to proper account on click.

Please 3.1 - thanks.

### CODE REVIEW

**Comment by mario** [comment]
cc @rullzer

File: src/gplay/java/com/owncloud/android/utils/PushUtils.java [hunk 1]
```diff
@@ -397,4 +399,78 @@ private static void migratePushKeys() {
...
+            Log.d(TAG, "No such algorithm");
+        } catch (InvalidKeyException e) {
+            Log.d(TAG, "Invalid key while trying to verify");
+        } catch (SignatureException e) {
+            Log.d(TAG, "Signature exception while trying to verify");
+        }
+
+        return signatureVerification;
+    }
+
```
[the remark this answers is not in the document]
Comment (mario) [reply src/gplay/java/com/owncloud/android/utils/PushUtils.java]: Useless complaint :P

[the remark this answers is not in the document]
Comment (mario) [reply src/gplay/java/com/owncloud/android/utils/PushUtils.java]: Didn't we ignore this with codacy @AndyScherzinger ?

**Comment by tobiasKaminsky** [comment]
Drone is faling on generic flavor

**Comment by mario** [comment]
@tobiasKaminsky can you copy/paste the errors please? :)

**Comment by AndyScherzinger** [comment]
```
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/PushMessage.java:27: warning: Parceler: Reflection is required to access private field: String signature, consider using non-private.
    private String signature;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/PushMessage.java:26: warning: Parceler: Reflection is required to access private field: String subject, consider using non-private.
    private String subject;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/PushMessage.java:27: warning: Parceler: Reflection is required to modify private field: String signature, consider using non-private.
    private String signature;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/PushMessage.java:26: warning: Parceler: Reflection is required to modify private field: String subject, consider using non-private.
    private String subject;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/SignatureVerification.java:28: warning: Parceler: Reflection is required to access private field: boolean signatureValid, consider using non-private.
    private boolean signatureValid;
                    ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/SignatureVerification.java:29: warning: Parceler: Reflection is required to access private field: Account account, consider using non-private.
    private Account account;
                    ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/SignatureVerification.java:28: warning: Parceler: Reflection is required to modify private field: boolean signatureValid, consider using non-private.
    private boolean signatureValid;
                    ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/SignatureVerification.java:29: warning: Parceler: Reflection is required to modify private field: Account account, consider using non-private.
    private Account account;
                    ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:26: warning: Parceler: Reflection is required to access private field: String app, consider using non-private.
    private String app;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:30: warning: Parceler: Reflection is required to access private field: String subject, consider using non-private.
    private String subject;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:32: warning: Parceler: Reflection is required to access private field: String id, consider using non-private.
    private String id;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:28: warning: Parceler: Reflection is required to access private field: String type, consider using non-private.
    private String type;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:26: warning: Parceler: Reflection is required to modify private field: String app, consider using non-private.
    private String app;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:30: warning: Parceler: Reflection is required to modify private field: String subject, consider using non-private.
    private String subject;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:32: warning: Parceler: Reflection is required to modify private field: String id, consider using non-private.
    private String id;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java:28: warning: Parceler: Reflection is required to modify private field: String type, consider using non-private.
    private String type;
                   ^
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/jobs/NotificationJob.java:81: error: cannot find symbol
                PrivateKey privateKey = (PrivateKey) PushUtils.readKeyFromFile(false);
                                                              ^
  symbol:   method readKeyFromFile(boolean)
  location: class PushUtils
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/jobs/NotificationJob.java:84: error: cannot find symbol
                    SignatureVerification signatureVerification = pushUtils.verifySignature(context,
                                                                           ^
  symbol:   method verifySignature(Context,byte[],byte[])
  location: variable pushUtils of type PushUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky fixed!

**Comment by mario** [comment]
Done! @tobiasKaminsky @AndyScherzinger

**Comment by AndyScherzinger** [comment]
@mario still fails to build:
```
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/jobs/NotificationJob.java:81: error: cannot find symbol
                PrivateKey privateKey = (PrivateKey) PushUtils.readKeyFromFile(false);
                                                              ^
  symbol:   method readKeyFromFile(boolean)
  location: class PushUtils
/drone/src/github.com/nextcloud/android/src/main/java/com/owncloud/android/jobs/NotificationJob.java:84: error: cannot find symbol
                    SignatureVerification signatureVerification = pushUtils.verifySignature(context,
                                                                           ^
  symbol:   method verifySignature(Context,byte[],byte[])
  location: variable pushUtils of type PushUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

**Comment by mario** [comment]
Will check.

**Comment by mario** [comment]
Hm only missing was version dev. pushed.

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky ready!

File: src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
+/*
+ * Nextcloud application
+ *
+ * @author Mario Danic
+ * Copyright (C) 2017-2017 Mario Danic <mario@lovelyhq.com>
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java]: Welcome to 2018 maybe? :grin:

Comment (mario) [reply src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java]: Fix pls.

**Comment by AndyScherzinger** [comment]
:+1: looks good code wise, haven't tested notifications in general recently...

File: src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java (hunk 2 above)
Comment (mario) [reply src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java]: Fixed.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky ping ;-)

File: src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseInstanceIDService.java [hunk 3]
```diff
@@ -39,4 +39,3 @@ public void onTokenRefresh() {
         }
     }
 }
-
```
Comment (tobiasKaminsky) [inline src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseInstanceIDService.java]: Shouldn't we keep this?

File: src/gplay/java/com/owncloud/android/utils/PushUtils.java [hunk 4]
```diff
@@ -397,4 +399,78 @@ private static void migratePushKeys() {
...
         }
     }
+
+    public SignatureVerification verifySignature(Context context, byte[] signatureBytes, byte[] subjectBytes) {
+        Signature signature = null;
+        PublicKey publicKey;
+        SignatureVerification signatureVerification = new SignatureVerification();
+        signatureVerification.setSignatureValid(false);
+
+        Account[] userEntities = AccountUtils.getAccounts(context);
```
Comment (tobiasKaminsky) [inline src/gplay/java/com/owncloud/android/utils/PushUtils.java]: This is better named account, or?

File: src/gplay/java/com/owncloud/android/utils/PushUtils.java [hunk 5]
```diff
@@ -397,4 +399,78 @@ private static void migratePushKeys() {
...
+            Log.d(TAG, "No such algorithm");
+        } catch (InvalidKeyException e) {
+            Log.d(TAG, "Invalid key while trying to verify");
+        } catch (SignatureException e) {
+            Log.d(TAG, "Signature exception while trying to verify");
+        }
+
+        return signatureVerification;
+    }
+
```
[the remark this answers is not in the document]
Comment (tobiasKaminsky) [reply src/gplay/java/com/owncloud/android/utils/PushUtils.java]: please also fix this

File: src/main/java/com/owncloud/android/jobs/NotificationJob.java [hunk 6]
```diff
@@ -0,0 +1,145 @@
...
+        String signature = persistableBundleCompat.getString(KEY_NOTIFICATION_SIGNATURE, "");
+
+        if (!TextUtils.isEmpty(subject) && !TextUtils.isEmpty(signature)) {
+
+            try {
+                PushMessage pushMessage = new PushMessage();
+                pushMessage.setSubject(subject);
+                pushMessage.setSignature(signature);
+
+                byte[] base64DecodedSubject = Base64.decode(pushMessage.getSubject(), Base64.DEFAULT);
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/jobs/NotificationJob.java]: What is the use here:
```
PushMessage pushMessage = new PushMessage();
pushMessage.setSubject(subject);
byte[] base64DecodedSubject = Base64.decode(pushMessage.getSubject(), Base64.DEFAULT);
```

this could be
`byte[] base64DecodedSubject = Base64.decode(subject, Base64.DEFAULT);`
or?

With this the complete PushMessage class is not needed?

**Comment by tobiasKaminsky** [comment]
What is the reason to use a job here? 
Can't we just do this all in NCFirebaseMessagingService.java?

File: src/gplay/java/com/owncloud/android/utils/PushUtils.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (mario) [reply src/gplay/java/com/owncloud/android/utils/PushUtils.java]: Ergh. This is a useless warning that I though we had disabled. but ok.

**Comment by mario** [comment]
All CR comments fixed. We need to use a job because in certain situations the decryption could take 10 seconds (or less in some ocassions) in which case work would be interrupted by the system.

**Comment by tobiasKaminsky** [comment]
:+1: 
Working, but on a separate PR (or on this if you want) we need to fix the theming:
- account a with theming blue
- account b with theming red
- on account a
- receive push for account b
- open up notification -> shows notification for b, but wtith theming blue (account a)

**Comment by tobiasKaminsky** [comment]
Theming is now changing according to new account :+1:
