### PR TITLE
Fix search loading animation and display

### LINKED ISSUE #9373: Empty placeholder flashes while loading
### Steps to reproduce
1. Open "Shared" or "Favorites" screen
2. Pull to refresh

(also happens during initial load) More screens may be affected.

### Expected behaviour
- Loading message appears

### Actual behaviour
- "No files here" appears for a short moment, before loading message does

### Environment data
Android version: 11 (sdk 30)

Device model: emulator

Stock or customized system: stock

Nextcloud app version: 3.18.0

Nextcloud server version: 22

Reverse proxy: no

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Fixes:
 - When switching search type (shared, favorites, etc), loading animation doesn't show 
 - When switching search type the empty message is displayed instead of "Loading..." (Fixes #9373)

- [x] Tests written, or not not needed

### CODE REVIEW

File: app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java [hunk 1]
```diff
@@ -1510,6 +1510,87 @@ public void onMessageEvent(final SearchEvent event) {
         handleSearchEvent(event);
     }
 
+    private static class SearchAsyncTask extends AsyncTask<Void, Void, Boolean> {
```
Comment (tobiasKaminsky) [inline app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java:1513]: Maybe we want to extract this class, so that Fragment file is not that big?

**Review by tobiasKaminsky — APPROVED** [review]

File: app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java (hunk 1 above)
Comment (AlvaroBrey) [reply app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java]: Done in  https://github.com/nextcloud/android/pull/9972/commits/769816978a1342d1c54b4cdb63e07e2e489d7c67
