### PR TITLE
Fix crash during text file creation

### LINKED ISSUE #5330: Crashes on text file creation
************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Fragment ChooseTemplateDialogFragment{1ad7093 (f00c3c25-0707-4359-87ea-31414ba1c1d5)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseTemplateDialogFragment.java:258)
	at com.owncloud.android.ui.dialog.ChooseTemplateDialogFragment$CreateFileFromTemplateTask.doInBackground(ChooseTemplateDialogFragment.java:211)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30100090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: starqltecs
Model: SM-G960W
Id: PPR1.180610.011
Product: starqltecs

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G960WVLS7CSL1

## Steps to reproduce
1. 'Create text file' menu option
2. Enter file name .md
3. Click Back button

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by ezaquarii**
Fixes #5330 

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### Testing 
Manual test only. Create a text file, invoking template chooser dialog.

### CODE REVIEW

File: src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java [hunk 1]
```diff
@@ -241,35 +242,36 @@ protected String doInBackground(Void... voids) {
...
-                    RemoteOperationResult newFileResult = new ReadFileRemoteOperation(path)
-                            .execute(client);
-
-                    if (newFileResult.isSuccess()) {
-                        OCFile temp = FileStorageUtils.fillOCFile((RemoteFile) newFileResult.getData().get(0));
-
-                        if (chooseTemplateDialogFragmentWeakReference.get() != null) {
-                            FileDataStorageManager storageManager = new FileDataStorageManager(
-                                user.toPlatformAccount(),
-                                chooseTemplateDialogFragmentWeakReference.get().requireContext().getContentResolver());
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java]: This is pretty common error I see. Both activities and fragments are passed as weak references to avoid leaks, but in case of fragment we must check if it has been detached.

File: src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java [hunk 2]
```diff
@@ -241,35 +242,36 @@ protected String doInBackground(Void... voids) {
...
+
+                OCFile temp = FileStorageUtils.fillOCFile((RemoteFile) newFileResult.getData().get(0));
+
+                final ChooseTemplateDialogFragment fragment = chooseTemplateDialogFragmentWeakReference.get();
+                if (fragment == null) {
+                    return "";
+                }
+
+                final Context context = fragment.getContext();
+                if (context == null) {
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java]: There is also "isAdded" or "isDetached", which we can use, or?

getContext is: return mHost == null ? null : mHost.getContext()
isAdded is: return mHost != null && mAdded

So isAdded might even the more extensive check, or?

Comment (ezaquarii) [reply src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java]: Yes, you can use that, as it calls `@NonNull FragmentHostCallback.getContext()`. I'll change it.

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java]: True.
Then let us keep it this way :+1:

**Comment by tobiasKaminsky** [comment]
Thanks for finding and fixing this bug :tada:
