### PR TITLE
Fixed crash during folder creation (autosync)

### LINKED ISSUE #4792: App crashes every time I try to create a new folder
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
	at com.owncloud.android.ui.dialog.CreateFolderDialogFragment.onClick(CreateFolderDialogFragment.java:139)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: star2qlteue
Model: SM-G965U1
Id: PPR1.180610.011
Product: star2qlteue

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: G965U1UEU7CSJ3

### PR DESCRIPTION
**Pull request by Shagequi**
Hi,
I fixed bug relative to folder picker, because mFile was always returning null.

Fixes #4792

### CODE REVIEW

**Comment by Shagequi** [comment]
It fixes https://github.com/nextcloud/android/issues/4792

File: src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
+package com.owncloud.android.ui.activity;
```
Comment (AndyScherzinger) [inline src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java]: @Shagequi can you add the license header please :)

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java [hunk 2]
```diff
@@ -302,7 +299,8 @@ public boolean onOptionsItemSelected(MenuItem item) {
         boolean retval = true;
         switch (item.getItemId()) {
             case R.id.action_create_dir: {
-                CreateFolderDialogFragment dialog = CreateFolderDialogFragment.newInstance(getCurrentFolder());
+                OCFile currentFolder = getCurrentFolder();
+                CreateFolderDialogFragment dialog = CreateFolderDialogFragment.newInstance(currentFolder);
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: no need to split this into two statements, could be reverted (or did I miss a detail here?)

**Comment by AndyScherzinger** [comment]
@Shagequi Just two minor issues 👍

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java (hunk 2 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: I guess this was just for debugging, but true, this can be reverted.

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java [hunk 3]
```diff
@@ -333,16 +331,24 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                return getStorageManager().getFileByPath(parentPath);
+        OCFile currentFile = getFile();
+        OCFile finalFolder = null;
+
+        // If the file is null, take the root folder to avoid any error in functions depending on this one
+        if (currentFile != null) {
+            if (currentFile.isFolder()) {
+                finalFolder = currentFile;
+            } else if(currentFile.getRemotePath() != null) {
+                String parentPath = currentFile
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: I would use new File(currentFile.getRemotePath()).getParent() for this.

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java (hunk 2 above)
Comment (Shagequi) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: Yup it was for debugging. 
I'm glad it's this name, I sometimes have an excess of imagination in my development (for naming variables or logs 😅)... 

I'll fix it ASAP, am working on another project

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java (hunk 3 above)
Comment (Shagequi) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: Yeah, I forgot this point too,
will be fixed asap too

File: src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java (hunk 1 above)
Comment (Shagequi) [reply src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java]: Sure, will be done

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java (hunk 3 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: "asap" -> do not hurry too much :-)

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java (hunk 2 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: Wo worries, no hurries :)

File: src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+@RunWith(AndroidJUnit4.class)
+@LargeTest
+public class FolderPickerActivityTest {
+    @Rule
+    public ActivityTestRule<FolderPickerActivity> activityRule =
+        new ActivityTestRule<>(FolderPickerActivity.class);
+
+    @Test
+    public void getFile_NoDifferenceTest() {
+        // Arrange
```
Comment (ezaquarii) [inline src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java]: I appreciate that we try to document he test. If we're writing a geherkin-style test scenarios, can we please use recognized way for this?
https://support.smartbear.com/cucumberstudio/docs/bdd/write-gherkin-scenarios.html

File: src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+
+@RunWith(AndroidJUnit4.class)
+@LargeTest
+public class FolderPickerActivityTest {
+    @Rule
+    public ActivityTestRule<FolderPickerActivity> activityRule =
+        new ActivityTestRule<>(FolderPickerActivity.class);
+
+    @Test
+    public void getFile_NoDifferenceTest() {
```
Comment (ezaquarii) [inline src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java]: test suffix is not needed;
it was needed in Junit3, bacause it was looking for a particularly named methods, but since JUnit4 uses annotations, we don't need it.

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java [hunk 6]
```diff
@@ -333,16 +331,24 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                        .getRemotePath()
+                        .substring(0, currentFile.getRemotePath()
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: Can we break those multiple statements? Readers generally expect 1 statement per line of code. Here we have 4.

File: src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java (hunk 3 above)
Comment (Shagequi) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: This method doesn't work, we need to use the FileStorageManager in all cases, I stay with this solution for now

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]:
```
String parentPath = new File(currentFile.getRemotePath()).getParent();

                String parentPath1 = currentFile
                        .getRemotePath()
                        .substring(0, currentFile.getRemotePath()
                        .lastIndexOf(currentFile.getFileName()));
```

Should be exactly the same, and is not error prone :-)

Comment (Shagequi) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: But, why create a `File` object, if we're expecting an OCFile object ?

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java]: This is just for handling the path part.
I think, using File, is more error prone than trying to to it by our selves.

**Comment by Shagequi** [comment]
@tobiasKaminsky Now it's done, would you please merge this important fix ?

File: src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java (hunk 4 above)
Comment (tobiasKaminsky) [reply src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityTest.java]: To be honest, I also do not follow this, and we did not agreed on a common pattern.
As I also now those three steps, we can keep it this way and discuss in separate issue, which way(s) we do want to follow

**Comment by tobiasKaminsky** [comment]
I rebased, added two tests and if everything is green, we can merge.

**Comment by Shagequi** [comment]
All the tests are green :D
