### PR TITLE
Use reloading on photo view

### LINKED ISSUE #1682: Photo section load endless
### Actual behaviour
photo section is loading endless. Monitoring Server show that the cpu use increase for an minute but the the app do not stop loading. thumbnails in "all files"-section are shown normal

### Expected behaviour
should show photos after created thumbnails on server
 
### Steps to reproduce
1. open app
2. click to photo seciton
3. 

### Environment data
Android version: 7.1.2

Device model: Nexus 5x with LineageOS

Stock or customized system: LineageOS

Nextcloud app version: 2.0.0

Nextcloud server version: 12.0.3

#### Web server error log
no specific error on server log, only Sabre\DAV\Exception\BadRequest: expected filesize 1343225856 got 57344 at same day but not same time

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### LINKED ISSUE #1901: Photo view: load new images when reaching bottom
Currently photo view tries to load all images that are stored on server and this results in very long waiting.
@rullzer had the idea to show first only the latest 7 days and when reaching the bottom of the list, then show/add again 7 days.
This would give the user at the beginning a very fast experience...

@mario it should be possible to limit the search to a certain timespan?

### LINKED ISSUE #1972: 3.0RC1: Favorites and Photos loading for ever
When selecting menu point "Favorites" or "Photos", the app shows "loading" and the "sandbox" circle does not stop spinning.  No content is shown.

### LINKED ISSUE #4235: Photos missing caching feature
### Actual behaviour
1) Photos (accessed from drawer) seem to be missing any sort of caching of thumbnail data. Each time when accessed, app will try to load all the photos from scratch. Since I have a good amount of photos on the cloud, it takes a lot of time.

### Expected behaviour
- Caching of the thumbnails is desired (probably cache as much data as possible, to prevent performance hiccups). Also, performance wise, I'd suggest that the app doesnt try to load all the photos at once, but perhaps just a few photos (50-60) and load more when user reaches the end of the list by scrolling. (Small enhancement plug - I view the photos as a very important segment of the app. Sorting and categorization by folders would be a great improvement.)
 
### Steps to reproduce
1. open Photos from the drawer
2. after photos are loaded, go back to Files
3. go back to Photos again, you will notice that all the photos load from 0

screen

### Environment data
Android version: 9
Nextcloud app version: 3.7.0
Nextcloud server version: 15 snap

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #4235 
Fix #1972 
Fix #1682 
Fix #1901 

*  [x] Needs: https://github.com/nextcloud/android-library/pull/134

Once this is merged, revert: https://github.com/nextcloud/android-library/pull/322

~~Stalled by:~~
~~https://github.com/nextcloud/server/issues/15029~~
~~https://github.com/nextcloud/server/issues/15048~~

This first loads 3x display items and on each bottom reach loads the next bunch of images.
Due to limitation of webdav this is currently only working if search is sorted by date, so not working on file names (for (favorite) search).

**BUGS:**
- [x] no loading dialog on start
- [x] swipe to refresh on photo search results in "/" file list
- [x] loading additional photos duplicates items, so after 3x we have 3x the first image
- [x] sort order is totally arbitrary
- [x] click on an image, return, sometimes show file list

**TODOs**
- [x] "cache" search: show photos, click on image, go back within 30s should show directly "old" search
- [x] try to re-use stored information, e.g. of parent folder
- [x] add check for NC14
- [x] check/fix navigation
- [x] maybe enhance loading with http://www.devexchanges.info/2017/02/android-recyclerview-dynamically-load.html

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This will be a NC14+ feature as it depends on changes on webdav search.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is this PR revive-able? Just asking because RecyclerView has already been merged and this PR has a lot of conflicts with master :/

**Comment by tobiasKaminsky** [comment]
I will try, once I have a bit space left.
I thought that I based this of recyclerview PR, but apparently something went wrong.

**Comment by AndyScherzinger** [comment]
recyclerview PR has already been merged, so maybe a rebase on master will solve most of the issues automatically?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you rebase this one and do you remember which commits belong to the PR and which are originally from the RecyclerView PR (which is already on master since quite a while)?

**Comment by tobiasKaminsky** [comment]
> Due to limitation of webdav this is currently only working if search is sorted by date, so not working on file names (for (favorite) search).

@rullzer as we both had at chat about the webdav search, is this still true?

But even if this is true, we can still use this for photo search, or?

**Comment by tobiasKaminsky** [comment]
I am working on this right now.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you rebase this beast? 🙈

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky can you rebase this beast?

uh oh :/

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky not sure what you did, definitely needs another rebase ;)

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky not sure what you did, definitely needs another rebase ;)

I squashed everything so that rebase onto master is easier.
This is currently only local, stay tuned :-P

**Comment by AndyScherzinger** [comment]
> This is currently only local, stay tuned :-P

I will :)

**Comment by tobiasKaminsky** [comment]
Update: needs first to solve server side search problems, see https://github.com/nextcloud/android-library/pull/134

**Comment by tobiasKaminsky** [comment]
But at least it is now up to date with masetr

**Comment by tobiasKaminsky** [comment]
Finally this is in a good looking shape.

Please test it, via provided APK.
Please focus on 
- correct ordering
- shows correct/all images?
- navigate to/from photos, is everything else still shown correctly?

**Comment by tobiasKaminsky** [comment]
APK file: https://www.kaminsky.me/nc-dev/android-artifacts/10000.apk <br/><br/> qrcode


Finally this is in a good looking shape.

Please test it, via provided APK.
Please focus on 
- correct ordering
- shows correct/all images?
- navigate to/from photos, is everything else still shown correctly?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you do a rebase, then I'll clone&test :)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger done.
You can also just use the provided APK instead of compiling it yourself ;-)

**Comment by pilsnerbeer** [comment]
Leaving some feedback as of v10052:

☑ Performance upgraded
☑ Thumbnails now load correctly and fast
☑ When tapped, thumbnails will load into full-size photos quickly
☑ Removed "No files" bug

😡 "Photos" stays selected on drawer even when its no longer focused
😡 Opening "Photos" after fully loading it in the past will sometimes bug it, causing the view to show scrambled photos with 50% of them having no thumbnail loaded. (Reproduce: files->photos->files->photos; sometimes it will work correctly, other times not)
😡 Opening Photos after caching them takes the same time as if opening for the first time. (This is linked to the previous bug - if they open fast from cache, it will lead to the scrambled half-loaded mess; if not, they will load correctly but very slowly).

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky lib PR has been fine and merged 👍

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky lib PR has been fine and merged

and this kills now master, as I removed two SearchTypes, (not your fault), but we need to have a way to prevent this.
I just do not know how.

I will try this now: https://github.com/apps/dep

**Comment by AndyScherzinger** [comment]
> ☑ Performance upgraded
☑ Thumbnails now load correctly and fast
☑ When tapped, thumbnails will load into full-size photos quickly
☑ Removed "No files" bug

> 😡 "Photos" stays selected on drawer even when its no longer focused

@tobiasKaminsky can be reprocduced and doesn't happen on master, Photos even stay focused when you do "Files"->"Photos"->"Files"->"Settings"->"Back" (still Photos gebing selected in the drawer menu)

> 😡 Opening "Photos" after fully loading it in the past will sometimes bug it, causing the view to show scrambled photos with 50% of them having no thumbnail loaded. (Reproduce: files->photos->files->photos; sometimes it will work correctly, other times not)

@tobiasKaminsky can be reprocduced while I think this is a general image loading issue with the current image fetching code (also on files lists)

> 😡 Opening Photos after caching them takes the same time as if opening for the first time. (This is linked to the previous bug - if they open fast from cache, it will lead to the scrambled half-loaded mess; if not, they will load correctly but very slowly).

@tobiasKaminsky not present for me, while I have the effect that sometime, for images where there hasn't been a preview been fetched I get a folder-icon display and errors when opening the image from the Phtoso view.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky not present for me, while I have the effect that sometime, for images where there hasn't been a preview been fetched I get a folder-icon display and errors when opening the image from the Phtoso view.

I started with a clean installation, thus no previews available and I always got at least an image placeholder.
Can you have a look which file this is? It should be indeed a folder, as we get the icon from the mimetype.

**Comment by tobiasKaminsky** [comment]
> scrambled photos

Really scrambled as in the preview is corrupt? oO

File: src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+                            if ((totalItemCount - visibleItemCount) > 0) {
+                                searchAndDisplay();
+                            }
+                        }
+                    }
+                }
+            }
+        };
+
+        Log_OC.i(this, "onCreateView() in PhotoFragment end");
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java]: Is that useful?

 I'd consider `v` - verbose level aka trace in other environments, something even more spammy than debug. We can then turn this noise off when new logger is ready.

File: src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java [hunk 2]
```diff
@@ -0,0 +1,185 @@
...
+                if (recyclerView.getLayoutManager() instanceof GridLayoutManager) {
+                    GridLayoutManager gridLayoutManager = (GridLayoutManager) recyclerView.getLayoutManager();
+
+                    // scroll down
+                    if (dy > 0 && !photoSearchQueryRunning) {
+                        int visibleItemCount = gridLayoutManager.getChildCount();
+                        int totalItemCount = gridLayoutManager.getItemCount();
+                        int firstVisibleItem = gridLayoutManager.findFirstCompletelyVisibleItemPosition();
+
+                        if ((totalItemCount - visibleItemCount) <= (firstVisibleItem + 5)) {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java]: I guess that this 5 is number of remaining items off-screen? Named `private final int` maybe?

File: src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java [hunk 3]
```diff
@@ -0,0 +1,185 @@
...
+    public void setPhotoSearchQueryRunning(boolean bool) {
+        photoSearchQueryRunning = bool;
+    }
+
+    /**
+     * Used to indicate that a paginated search was done, but did not result in new results
+     *
+     * @param bool true if search ran, but no new photos were retrieved; then no new search will be started
+     */
+    public void setPhotoSearchNoNew(boolean bool) {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java]: `noNewItemsFound`?

**Comment by mlaverdiere** [comment]
I'm testing the PR and I can confirm that it works way better. Thanks!

2 comments though:

1) Like already reported, reopening Photos after caching them takes the same time as if opening for the first time.

2) I 'm on Pixel 2, which allows (like some other Andoid devices) to shoot photos in RAW (dng) format, that Nextcloud is usually not able to show/render (there's a specific app for the web sever to render RAW fles, but I'm not sure that it allows the Andoid app to do so...). Anyway, as it is right now, the Photo section shows JPGs files correctly, along with some all grey icons for RAWs (dng). I think that it would be more elegant (and maybe quicker) if the Photo sections was just showing what it can render correctly, i.e. JPGs (and I guess PNG and some other non RAW formats) and avoid to show useless/ugly grey icons for RAWs. The RAW files, when they are uploaded/synced could still be seen in their specific folders (whether it is in InstantUpload or other folders).

My 2 cents!

File: src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java (hunk 1 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java]: It is just c&p from OCFileListFragment.
These kind of "debug infos" area spread all over the app…
I am also not user if we need them, -> better discuss it a new issue.

File: src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java (hunk 2 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java]: Changed, not sure if it named the best way.
But with this threshold we make sure that at least one row is completely shown. (10 is max column size in landscape mode)

File: src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java (hunk 3 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java]: Maybe you have a better overall approach to this? :-)

**Comment by tobiasKaminsky** [comment]
@mlaverdiere 
1) I still do not find a way why this is happening… :/
2) We do get the previews from server, so if server can support raw previews, you will see them. Maybe this one: https://apps.nextcloud.com/apps/camerarawpreviews

**Comment by tobiasKaminsky** [comment]
@ezaquarii I changed code according to your review, thank you :-)

File: src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java [hunk 4]
```diff
@@ -2563,6 +2580,25 @@ public void showFiles(boolean onDeviceOnly) {
         getListOfFilesFragment().refreshDirectory();
     }
 
+    @Subscribe(threadMode = ThreadMode.BACKGROUND)
+    public void onMessageEvent(final SearchEvent event) {
+        Fragment fragment;
+
+        if (SearchRemoteOperation.SearchType.PHOTO_SEARCH.equals(event.searchType)) {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java]: For enums, you can use `==`.

File: src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+import com.owncloud.android.lib.common.utils.Log_OC;
+import com.owncloud.android.lib.resources.files.SearchRemoteOperation;
+import com.owncloud.android.ui.activity.ToolbarActivity;
+import com.owncloud.android.ui.adapter.OCFileListAdapter;
+import com.owncloud.android.ui.fragment.ExtendedListFragment;
+import com.owncloud.android.ui.fragment.PhotoFragment;
+
+import java.lang.ref.WeakReference;
+
+public class PhotoSearchTask extends AsyncTask<Void, Void, RemoteOperationResult> {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java]: We could consider migrating this to new `AsyncRunner`. Few benefits:

1. task turns into a simple function which you can actually unit test
2. `onPostExectute` turns into another function and moves to relevant UI class where it belongs

File: src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+            searchRemoteOperation.setLimit(limit);
+            searchRemoteOperation.setTimestamp(timestamp);
+
+            return searchRemoteOperation.execute(account, photoFragment.requireContext());
+        }
+    }
+
+    @Override
+    protected void onPostExecute(RemoteOperationResult result) {
+        if (photoFragmentWeakReference.get() != null) {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java]: I'm not sure ithis UI code belongs here.

File: src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java [hunk 7]
```diff
@@ -1446,10 +1449,14 @@ public void onMessageEvent(FavoriteEvent event) {
 
     @Subscribe(threadMode = ThreadMode.BACKGROUND)
     public void onMessageEvent(final SearchEvent event) {
+        if (SearchRemoteOperation.SearchType.PHOTO_SEARCH.equals(event.searchType)) {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java]: `==`

File: src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java (hunk 5 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java]: Let us do this in an additional PR.
This one is already too old and too big.

File: src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java (hunk 6 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java]: Let us also do this in the same new PR as above.

**Comment by mlaverdiere** [comment]
Just tested the latest 10374.apk build.

First, selecting the images section in the left panel  seemed to load faster than previous test-build, buf it loaded only 13 images (quite old, not the latest one that I have taken with my phone or uploaded on my account...), and then stop, with the loading spinning wheel. 

Switching to other app. and coming back to ND and selecting the images section in the left panel does nothing good, i.e. only showing 13 grey icons.  Switching to other app. and coming back to ND and selecting the images section in the left panel does nothing, i.e. only showing 13 grey icons. 

Doing the same thing again show the 13 images that were first displayed, without nothing else except showing the loading spinning wheel.

**Comment by tobiasKaminsky** [comment]
Spotbugs fails to detect logic here:

```
Possible null pointer dereference in com.owncloud.android.ui.asynctasks.PhotoSearchTask.onPostExecute(RemoteOperationResult) due to return value of called method
--
  | Bug type NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE (click for details)In class 
com.owncloud.android.ui.asynctasks.PhotoSearchTaskIn method 
com.owncloud.android.ui.asynctasks.PhotoSearchTask.onPostExecute(RemoteOperationResult)
Value loaded from photoFragmentDereferenced at PhotoSearchTask.java:[line 
115]Known null at PhotoSearchTask.java:[line 97]
```

https://github.com/nextcloud/android/blob/46fdd578f89f9a9d0cb5389567d706ab4f36110c/src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java#L96-L115

I check at L96 if it is null, and then use it at 115, where it can never been null.

No idea what to do here to prevent Spotbugs from behaving wrong.
So I change spotbugs-result for now.

**Comment by tobiasKaminsky** [comment]
@ezaquarii @AndyScherzinger I would like to get this into 3.8.0 RC1, which is scheduled for next Monday.
As this is an isolated enhancement of a currently non-working feature, I think this is better than nothing.

**Comment by tobiasKaminsky** [comment]
IT test failure are unrelated.
Codacy is somehow true, but this is old code, which just was moved, so I would like to keep it this way and tackle it later

**Comment by AndyScherzinger** [comment]
Fine with me :

**Comment by AndyScherzinger** [comment]
Awaiting feedback from @ezaquarii :)

**Comment by mlaverdiere** [comment]
I just tried the latest 10407.apk and it works way better than the previous 10374.apk (and that the current stable release): pictures are loading (relatively...) fast the first time the pictures section is clicked and when coming back, it's much (relatively...) faster since it seems it doesn't try to reload completely the pictures but instead relie on cache data. Also, pictures are displayed in some logical order, i.e. pictures last taken (or modified/loaded I guess) are displayed first. 

I would say that, at last, with these fixes, the pictures section of the ND app. would be usable. Thanks!

**Comment by mlaverdiere** [comment]
Oops.. I did some other tests that were not so conclusive: upon exiting and coming back to the ND app, only grey icons were displayed in the pictures section and eventually, the app. crashed repetitively... Once I could get the pictures showing up again, it seemed that after it managed to display 95 images, it started to endlessly try to load the next ones, without any result...

**Comment by ezaquarii** [comment]
@mlaverdiere do you have the crash stacktrace?

**Comment by mlaverdiere** [comment]
Sorry, but how could I get the stacktrace? (just a regular user here, so I need some guidance...)

10424.apk loads pictures very fast, without any crash (so far), but again, stops after the first 95 images (endless spinning wheel)

**Comment by ezaquarii** [comment]
@mlaverdiere I'd expect you get a stacktrace displayed in a popup upon crash. It looks like this PR is behind master.

I created another test build for you. This one should display the stack trace popup on crash: #4339

**Comment by mlaverdiere** [comment]
OK, i just tested the 10427 build: no crash to report yet, but still stops after 95 pictures...

**Comment by gessel** [comment]
as #1682 and #6138 are closed and redirect here:

Photos pane in android app isn't working; I switched from release to dev and tried with Nextcloud-android/20200707,  it seems to time out and eventually (after 30-60 seconds or so) gives the No Photos/Upload some photos or activate auto upload.  The Photos App on the server works as expected (and there are definitely photos).

Model: SM-N950N
Brand: samsung
Product: greatlteks
Device: greatlteks
Version-Codename: REL
Version-Release: 9 


```
Server Logs (level 1)

{"reqId":"VNaduzAIUIfGiDbVkBpz","level":1,"time":"2020-07-09T12:49:56+00:00","remoteAddr":"dev.ip.ad.dr","user":"gessel","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20200707","version":"19.0.0.12"}
{"reqId":"2D2TRdESnekNINCv8ilc","level":1,"time":"2020-07-09T12:49:57+00:00","remoteAddr":"dev.ip.ad.dr","user":"gessel","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20200707","version":"19.0.0.12"}

Server log (level 0)

{"reqId":"dCOY2yvY6GlvZbY9hzaJ","level":0,"time":"2020-07-09T14:26:08+00:00","remoteAddr":"dev.ip.ad.dr","user":"gessel","app":"workflowengine","method":"SEARCH","url":"/remote.php/dav","message":"Flow activation: rules were requested for operation Block access to a file","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20200707","version":"19.0.0.12"}
{"reqId":"dCOY2yvY6GlvZbY9hzaJ","level":0,"time":"2020-07-09T14:26:08+00:00","remoteAddr":"dev.ip.ad.dr","user":"gessel","app":"workflowengine","method":"SEARCH","url":"/remote.php/dav","message":"No flow configurations is going to run Block access to a file","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20200707","version":"19.0.0.12"}

This request ID:

 # grep dCOY2yvY6GlvZbY9hzaJ /var/log/nextcloud.log | wc -l
   70490


Device Logs

2020-07-09T15:49:50.482+0300;D;LogsActivity;onPause() ending
2020-07-09T15:49:50.505+0300;D;SettingsActivity;onStart() starting
2020-07-09T15:49:50.508+0300;D;SettingsActivity;onResume() starting
2020-07-09T15:49:50.943+0300;D;LogsActivity;onStop() ending
2020-07-09T15:49:50.945+0300;D;LogsActivity;onDestroy() ending
2020-07-09T15:49:51.785+0300;D;SettingsActivity;onPause() ending
2020-07-09T15:49:51.817+0300;V;BaseActivity;onRestart() start
2020-07-09T15:49:51.823+0300;D;FileDisplayActivity;onStart() starting
2020-07-09T15:49:51.833+0300;D;OwnCloudClient #3;REQUEST GET /ocs/v2.php/cloud/capabilities
2020-07-09T15:49:51.839+0300;D;AdvancedSslSocketFactory;Creating SSL Socket with remote serv.domain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@1ca67c2
2020-07-09T15:49:51.839+0300;D;AdvancedSslSocketFactory; ... with connection timeout 5000 and socket timeout 40000
2020-07-09T15:49:51.841+0300;I;ServerNameIndicator;SSLSocket implementation: org.conscrypt.Java8FileDescriptorSocket
2020-07-09T15:49:51.841+0300;I;ServerNameIndicator;SNI done, hostname: serv.domain.com
2020-07-09T15:49:51.855+0300;D;OwnCloudClient #3;REQUEST GET /ocs/v1.php/cloud/user
2020-07-09T15:49:51.857+0300;D;AdvancedSslSocketFactory;Creating SSL Socket with remote serv.domain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@fc30ab4
2020-07-09T15:49:51.857+0300;D;AdvancedSslSocketFactory; ... with connection timeout 5000 and socket timeout 40000
2020-07-09T15:49:51.858+0300;I;ServerNameIndicator;SNI done, hostname: serv.domain.com
2020-07-09T15:49:51.874+0300;V;FileDisplayActivity;onResume() start
2020-07-09T15:49:51.876+0300;D;FileDisplayActivity;onResume() starting
2020-07-09T15:49:51.960+0300;V;FileDisplayActivity;onResume() end
2020-07-09T15:49:51.986+0300;V;OCFileListFragment;Kept the options menu default structure
2020-07-09T15:49:52.025+0300;D;OCFileListAdapter;sharees of barzan: [com.owncloud.android.lib.resources.shares.ShareeUser@de5fbe3]
2020-07-09T15:49:52.045+0300;D;OCFileListAdapter;sharees of BRT-LLC: []
2020-07-09T15:49:52.145+0300;D;OCFileListAdapter;sharees of PD: [com.owncloud.android.lib.resources.shares.ShareeUser@a45c2b7]
2020-07-09T15:49:52.448+0300;D;OwnCloudClient #3;REQUEST GET /status.php
2020-07-09T15:49:52.450+0300;D;AdvancedSslSocketFactory;Creating SSL Socket with remote serv.domain.com:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@7550b3f
2020-07-09T15:49:52.450+0300;D;AdvancedSslSocketFactory; ... with connection timeout 5000 and socket timeout 40000
2020-07-09T15:49:52.451+0300;I;ServerNameIndicator;SNI done, hostname: serv.domain.com
2020-07-09T15:49:52.898+0300;D;SettingsActivity;onStop() ending
2020-07-09T15:49:52.899+0300;D;SettingsActivity;onDestroy() ending
2020-07-09T15:49:54.186+0300;D;GetCapabilitiesRemoteOperation;Successful response: {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":19,"minor":0,"micro":0,"string":"19.0.0","edition":"","extendedSupport":false},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php\/webdav"},"bruteforce":{"delay":0},"password_policy":{"minLength":10,"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"api":{"generate":"https:\/\/serv.domain.com\/ocs\/v2.php\/apps\/password_policy\/api\/v1\/generate","validate":"https:\/\/serv.domain.com\/ocs\/v2.php\/apps\/password_policy\/api\/v1\/validate"}},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"directEditing":{"url":"https:\/\/serv.domain.com\/ocs\/v2.php\/apps\/files\/api\/v1\/directEditing","etag":"6226ba873373f5e73a3ef504107523f7"},"versioning":true,"undelete":true},"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"ocm":{"enabled":true,"apiVersion":"1.0-proposal1","endPoint":"https:\/\/serv.domain.com\/index.php\/ocm","resourceTypes":[{"name":"file","shareTypes":["user","group"],"protocols":{"webdav":"\/public.php\/webdav\/"}}]},"dav":{"chunking":"1.0"},"files_sharing":{"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false,"askForOptionalPassword":false},"expire_date":{"enabled":false},"multiple_links":true,"expire_date_internal":{"enabled":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false,"expire_date":{"enabled":true}},"group_sharing":true,"group":{"enabled":true,"expire_date":{"enabled":true}},"default_permissions":1,"federation":{"outgoing":false,"incoming":false,"expire_date":{"enabled":true}},"sharee":{"query_lookup_default":false},"sharebymail":{"enabled":true,"upload_files_drop":{"enabled":true},"password":{"enabled":true},"expire_date":{"enabled":true}}},"fulltextsearch":{"remote":true,"providers":[]},"notes":{"api_version":["0.2","1.1"],"version":"3.6.0"},"notifications":{"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings","action-web"],"push":["devices","object-data","delete"],"admin-notifications":["ocs","cli"]},"spreed":{"features":["audio","video","chat-v2","conversation-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","mention-flag","in-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","chat-read-marker","webinary-lobby","start-call-flag","chat-replies","circles-support","force-mute","chat-reference-id"],"config":{"attachments":{"allowed":true,"folder":"\/Talk"},"chat":{"max-length":32000},"conversations":{"can-create":true}}},"theming":{"name":"BRT NetNAS","url":"https:\/\/www.blackrosetech.com\/","slogan":"a safe home for all your data","color":"#351111","color-text":"#ffffff","color-element":"#351111","logo":"https:\/\/serv.domain.com\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=7","background":"#351111","background-plain":true,"background-default":true,"logoheader":"https:\/\/serv.domain.com\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=7","favicon":"https:\/\/serv.domain.com\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=7"}}}}}
2020-07-09T15:49:54.188+0300;D;GetCapabilitiesRemoteOperation;*** Added version
2020-07-09T15:49:54.188+0300;D;GetCapabilitiesRemoteOperation;*** Added core
2020-07-09T15:49:54.188+0300;D;GetCapabilitiesRemoteOperation;*** Added files_sharing
2020-07-09T15:49:54.188+0300;D;GetCapabilitiesRemoteOperation;*** Added files
2020-07-09T15:49:54.189+0300;D;GetCapabilitiesRemoteOperation;*** Added theming
2020-07-09T15:49:54.189+0300;D;GetCapabilitiesRemoteOperation;*** Added notifications
2020-07-09T15:49:54.189+0300;D;GetCapabilitiesRemoteOperation;*** Get Capabilities completed 
2020-07-09T15:49:54.243+0300;D;UpdateOCVersionOperation;Got new OC version 19.0.0.12
2020-07-09T15:49:54.243+0300;I;UpdateOCVersionOperation;Check for update of Nextcloud server version at https://serv.domain.com/remote.php/webdav: Operation finished with HTTP status code -1 (success)
2020-07-09T15:49:54.250+0300;D;ExternalLinks;links disabled
2020-07-09T15:49:54.269+0300;D;OwnCloudClient #3;REQUEST GET /ocs/v2.php/cloud/capabilities
2020-07-09T15:49:54.742+0300;D;GetCapabilitiesRemoteOperation;Capabilities not modified
2020-07-09T15:49:54.742+0300;D;GetCapabilitiesRemoteOperation;*** Get Capabilities completed 
2020-07-09T15:49:54.778+0300;D;OwnCloudClient #3;REQUEST GET /ocs/v1.php/cloud/user
2020-07-09T15:49:55.382+0300;I;RefreshFolderOperation;Got display name: com.owncloud.android.lib.common.UserInfo@c26442c
2020-07-09T15:49:55.383+0300;D;RefreshFolderOperation;Checking changes in gessel@serv.domain.com/
2020-07-09T15:49:55.398+0300;D;OwnCloudClient #3;REQUEST PROPFIND /remote.php/webdav/
2020-07-09T15:49:55.874+0300;I;RefreshFolderOperation;Checked gessel@serv.domain.com/ : changed
2020-07-09T15:49:55.880+0300;D;OwnCloudClient #3;REQUEST PROPFIND /remote.php/webdav/
2020-07-09T15:49:56.002+0300;V;OCFileListFragment;Kept the options menu default structure
2020-07-09T15:49:57.481+0300;V;OCFileListFragment;Kept the options menu default structure
2020-07-09T15:49:57.498+0300;V;FileDisplayActivity;onPause() start
2020-07-09T15:49:57.499+0300;D;FileDisplayActivity;onPause() ending
2020-07-09T15:49:57.500+0300;V;FileDisplayActivity;onPause() end
2020-07-09T15:49:57.501+0300;D;FileDisplayActivity;Switch to photo search fragment
2020-07-09T15:49:57.502+0300;V;FileDisplayActivity;onResume() start
2020-07-09T15:49:57.503+0300;D;FileDisplayActivity;onResume() starting
2020-07-09T15:49:57.507+0300;I;OCFileListFragment;onAttach
2020-07-09T15:49:57.511+0300;I;OCFileListFragment;onCreateView() start
2020-07-09T15:49:57.511+0300;D;ExtendedListFragment;onCreateView
2020-07-09T15:49:57.545+0300;I;OCFileListFragment;onCreateView() end
2020-07-09T15:49:57.545+0300;I;PhotoFragment;onCreateView() in PhotoFragment end
2020-07-09T15:49:57.546+0300;I;OCFileListFragment;onActivityCreated() start
2020-07-09T15:49:57.573+0300;D;OwnCloudClient #3;REQUEST OPTIONS /remote.php/dav
2020-07-09T15:49:57.592+0300;V;FileDisplayActivity;onResume() end
2020-07-09T15:49:57.809+0300;I;ReadFolderRemoteOperation;Synchronized /: Operation finished with HTTP status code 207 (success)
2020-07-09T15:49:57.809+0300;D;RefreshFolderOperation;Synchronizing gessel@serv.domain.com/
2020-07-09T15:49:57.813+0300;D;RefreshFolderOperation;Remote folder / changed - starting update of local data 
2020-07-09T15:49:57.828+0300;D;FileDataStorageManager;Saving folder / with 22 children and 0 files to remove
2020-07-09T15:49:57.913+0300;D;FileDataStorageManager;Sending 23 operations to FileContentProvider
2020-07-09T15:49:57.914+0300;D;FileContentProvider;applying batch in provider com.owncloud.android.providers.FileContentProvider@6740ebd (temporary: false)
2020-07-09T15:49:57.947+0300;D;FileContentProvider;applied batch in provider com.owncloud.android.providers.FileContentProvider@6740ebd
2020-07-09T15:49:57.948+0300;D;OwnCloudClient #3;REQUEST SEARCH /remote.php/dav
2020-07-09T15:49:57.958+0300;D;RefreshFolderOperation;Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
2020-07-09T15:49:57.959+0300;D;OwnCloudClient #3;REQUEST GET /ocs/v2.php/apps/files_sharing/api/v1/shares
2020-07-09T15:49:58.936+0300;D;GetSharesForFileRemoteOperation;Got 7 shares
2020-07-09T15:49:58.960+0300;D;FileDataStorageManager;Sending 29 operations to FileContentProvider
2020-07-09T15:49:58.960+0300;D;FileContentProvider;applying batch in provider com.owncloud.android.providers.FileContentProvider@6740ebd (temporary: false)
2020-07-09T15:49:59.004+0300;D;FileContentProvider;applied batch in provider com.owncloud.android.providers.FileContentProvider@6740ebd
2020-07-09T15:49:59.004+0300;D;RefreshFolderOperation;Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
2020-07-09T15:50:49.312+0300;V;FileDisplayActivity;onPause() start
2020-07-09T15:50:49.314+0300;D;FileDisplayActivity;onPause() ending
2020-07-09T15:50:49.314+0300;V;FileDisplayActivity;onPause() end
2020-07-09T15:50:49.338+0300;D;SettingsActivity;onCreate(Bundle) starting
2020-07-09T15:50:49.388+0300;D;SettingsActivity;onStart() starting
2020-07-09T15:50:49.390+0300;D;SettingsActivity;onResume() starting
2020-07-09T15:50:49.851+0300;D;FileDisplayActivity;onStop() ending
2020-07-09T15:50:49.852+0300;V;FileDisplayActivity;onSaveInstanceState() start
2020-07-09T15:50:49.852+0300;D;FileDisplayActivity;onSaveInstanceState(Bundle) starting
2020-07-09T15:50:49.853+0300;D;ExtendedListFragment;onSaveInstanceState()
2020-07-09T15:50:49.853+0300;V;FileDisplayActivity;onSaveInstanceState() end
2020-07-09T15:50:52.167+0300;D;SettingsActivity;onPause() ending
2020-07-09T15:50:52.186+0300;D;LogsActivity;onCreate(Bundle) starting
```

**Comment by svenb1234** [comment]
Same here with NC 18.0.6 and a Pixel 3a with the current Nextcloud App 3.12.1. Usually it only took unjustifiable long before the pictures appears, now it always times out.

It also seems to be not easy to debug the app for a user, such as logging its requests to the server or some debugging console as browsers have it for debugging websites.

**Comment by AndyScherzinger** [comment]
> It also seems to be not easy to debug the app for a user, such as logging its requests to the server or some debugging console as browsers have it for debugging websites.

The dev and debug builds do ship such a log view (accessible via the settings screen within the app) while this a general logging view, not one just for network communication

**Comment by AndyScherzinger** [comment]
other than that this is a (merged) PR, so it would be best to create an issue since discussions in merged, old PRs are rather getting lost in the Github notification noise
