### PR TITLE
TextDrawable: handle spaces at start/end of displayNames

### LINKED ISSUE #9887: StringIndexOutOfBoundsException in com.owncloud.android.ui.fragment.contactsbackup.BackupListAdapter.onBindViewHolder
'
https://user-images.githubusercontent.com/28694676/155557371-3f3ab36f-b6c4-41f5-b4e2-623421ec3a73.mp4

************ CAUSE OF ERROR ************

java.lang.StringIndexOutOfBoundsException: length=0; index=1
	at java.lang.String.substring(String.java:2060)
	at com.owncloud.android.ui.TextDrawable.extractCharsFromDisplayName(TextDrawable.java:145)
	at com.owncloud.android.ui.TextDrawable.createNamedAvatar(TextDrawable.java:132)
	at com.owncloud.android.ui.fragment.contactsbackup.BackupListAdapter.bindContactViewHolder(BackupListAdapter.kt:210)
	at com.owncloud.android.ui.fragment.contactsbackup.BackupListAdapter.onBindViewHolder(BackupListAdapter.kt:129)
	at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:305)
	at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:15)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:325)
	at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:15)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1144)
	at android.view.View.layout(View.java:22491)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8884)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

************ APP INFORMATION ************
ID: com.nextcloud.android.beta
Version: 20220222
Build flavor: versionDev

************ DEVICE INFORMATION ************
Brand: HONOR
Device: HWCOL
Model: COL-AL10
Id: HUAWEICOL-AL10
Product: COL-AL10

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: 10.0.0.179C00
`

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Fixes #9887

- [x] Tests written, or not not needed

### CODE REVIEW

File: app/src/test/java/com/owncloud/android/ui/TextDrawableTest.kt [hunk 1]
```diff
@@ -23,17 +23,43 @@ package com.owncloud.android.ui
 
 import org.junit.Assert.assertEquals
 import org.junit.Test
+import org.junit.runner.RunWith
+import org.junit.runners.Parameterized
 
+@RunWith(Parameterized::class)
```
Comment (tobiasKaminsky) [inline app/src/test/java/com/owncloud/android/ui/TextDrawableTest.kt:29]: Wow. That is cool!

**Review by tobiasKaminsky — APPROVED** [review]
