### PR TITLE
OcFileListFragment: throttle overflow menu clicks

### LINKED ISSUE #9319: File menus overlapping because multiple can be opened at the same time
### Steps to reproduce
1. Tap on two files' More icons (three dots)

### Expected behaviour
Only the last one's menu should be opened. Even if the clicks are at the same time, the events should be separate.

### Actual behaviour
Both menus open and overlap each other

### Environment data
Android version: 11

Device model:  Xiaomi Mi 9T Pro

Stock or customized system: LineageOS-based

Nextcloud app version: 3.18.0

Nextcloud server version: 22

Reverse proxy: no

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Fixes #9319

- [x] Tests written, or not not needed

### CODE REVIEW

File: src/main/java/com/owncloud/android/utils/Throttler.kt [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program. If not, see <https://www.gnu.org/licenses/>.
+ */
+package com.owncloud.android.utils
+
+import android.util.ArrayMap
+import com.nextcloud.client.core.Clock
+
+// TODO write tests
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/utils/Throttler.kt:26]: Please remove, write some or note it down as a task for later :)

**Review by tobiasKaminsky — APPROVED** [review]

File: src/main/java/com/owncloud/android/utils/Throttler.kt (hunk 1 above)
Comment (AlvaroBrey) [reply src/main/java/com/owncloud/android/utils/Throttler.kt]: https://github.com/nextcloud/android/pull/9435/commits/e138bb7175e15b71a8340c297e9c9070fcc28019
