### PR TITLE
Run contacts backup job only when network is connected

### LINKED ISSUE #9632: Daily backup of contacts and calendar not working
### Steps to reproduce
1. Activate the daily backup of contacts and calendar
2. Wait a few days
3. Have a look at the backup folders 

### Expected behaviour
- A daily backup should have happened and the date of the last backup should match with the information in the backup settings

### Actual behaviour
- No automatic backups happened. In the backup settings it says "Last backup: 4 hours ago" but the most recent file in .Calendar-Backup and .Contacts-Backup are four days old (that was a manually triggered backup)

### Can you reproduce this problem on https://try.nextcloud.com?
I didn't try, but I guess this is a client problem, not a server problem

### Environment data
Android version: 11

Device model: Fairphone 4 5G

Stock or customized system: Fairphone OS

Nextcloud app version: 3.18.1

Nextcloud server version:  20.0.11.1

### PR DESCRIPTION
**Pull request by ezaquarii**
Apply network constrains to prevent daily backup
job being started without network.

Backup job restart is required to apply new constraints.

Similar migration has been applied in the past, but migration
manager does not support re-applying steps again.

Migrations manager has been refactored to make migration
step re-applying easier, as more job restarts can be
required in the future.

Fixes #9632

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

- [x] Tests written, or not not needed

### CODE REVIEW

File: src/main/java/com/nextcloud/client/migrations/Migrations.kt [hunk 1]
```diff
@@ -55,75 +55,82 @@ class Migrations @Inject constructor(
...
+            logger.i(TAG, "$s: no users to migrate")
+        } else {
+            users.forEach {
+                val backupEnabled = arbitraryDataProvider.getBooleanValue(
+                    it.accountName,
+                    ContactsPreferenceActivity.PREFERENCE_CONTACTS_AUTOMATIC_BACKUP
+                )
+                if (backupEnabled) {
+                    jobManager.schedulePeriodicContactsBackup(it)
                 }
```
Comment (AlvaroBrey) [inline src/main/java/com/nextcloud/client/migrations/Migrations.kt:115]: `PREFERENCE_CONTACTS_AUTOMATIC_BACKUP` confusingly controls periodic backup for both contacts and calendar. This does not affect this PR but I'll create an issue to track that as well.

**Review by AlvaroBrey — APPROVED** [review]
