### PR TITLE
Make the name collision policy for auto uploads selectable

### LINKED ISSUE #4260: auto-upload and WhatsApp backups
### Actual behaviour

When auto-upload uploads WhatsApp backups files it perfectly uploads the file from the last day (which has a date indication like `msgstore-2019-07-25.dB.crypt12 `) but it creates a conflict with the backup of the day (which has no date indication like `msgstore.dB.crypt12 `) as a file with the same name already exists on the server.

The error message is (in french) `Conflit de synchronisation, Veuillez le résoudre manuellement`

### Expected behaviour
All WhatsApp backups should be successfully uploaded. The backup of the day should replace the previous one on the server (and with version enabled, should create a new version).
 
### Steps to reproduce
1. Configure WhatsApp backups for local storage
2. Add auto-upload on the local folder containing WhatsApp backups files
3. Wait for an auto-upload and another. The first auto-upload will create the backup of the day file on the server, the second auto-upload will show the error message

### LINKED ISSUE #5599: File duplication error
With 3.11 RC1 I get a file dupliccation error.

Files they are at NC won't be overwritten with newly update since 3.11 RC1.
I have to delete same named old files in NC before auto upload can upload these files.
Version's before aren't affected.

In my case I'll upload WhatsApp Backups to my NC storage.

Thanks for fixing or rolling back.

### LINKED ISSUE #5755: Sync conflict
### Steps to reproduce
Change nothing in existing auto-upload settings. Make sure new files are created in the folder configured for auto-upload.
or
Attempt manual file upload (files do not exist on the server)

I suspect this is started after the latest (3.11.0) update.

### Expected behaviour
Files are uploaded

### Actual behaviour
Files are not uploaded.

Notification: "File upload conflict. Pick which version to keep of \<filename\>"

In the app, in the "Uploads" screen, files are in the "Failed/pending restart" category with the message: "Sync conflict, please resolve manually". Pressing "Resolve conflict" does nothing. Pressing "Delete" does not delete anything, but attempts to upload are stopped.

## Server configuration detail

**Operating system:** Linux 4.4.110 #62 SMP Fri Jan 5 20:38:04 EET 2018 x86_64

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 10.0.38

**PHP version:** 

7.0.33-0ubuntu0.16.04.12
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 15.0.14 - 15.0.14.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** I don't remember

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - dav: 1.8.2
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.6.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - support: 1.0.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.14.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "loglevel": 1,
    "theme": "",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "htaccess.RewriteBase": "\/",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Android version:** 9
**Device model:** SM-G930F
**Stock or customized system:** LineageOS
**Nextcloud app version:** 3.11.0

## Logs

<details><summary>Web server error log</summary>

```
2020/03/27 22:20:48 [info] 64263#64263: *1162408 client <IP> closed keepalive connection
2020/03/27 22:20:48 [info] 64263#64263: *1162406 client <IP> closed keepalive connection
2020/03/27 22:21:27 [info] 64263#64263: *1162427 client <IP> closed keepalive connection
```
</details>

<details><summary>Nextcloud log</summary>

```
Empty
```
</details>

<details><summary>Web server access log</summary>

```
<IP> - phone [27/Mar/2020:22:43:25 +0200] "HEAD /remote.php/webdav/IMG_20200327_163254.jpg HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.0"
<IP> - phone [27/Mar/2020:22:43:25 +0200] "HEAD /apps/files/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.0"
<IP> - phone [27/Mar/2020:22:43:25 +0200] "HEAD /remote.php/webdav/IMG_20200327_163714.jpg HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.0"
<IP> - phone [27/Mar/2020:22:43:25 +0200] "HEAD /apps/files/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.0"
```
</details>

### LINKED ISSUE #5827: Upload of WhatsApp Backup failed
### Steps to reproduce
1. Create WhatsApp Chat Backup locally 
2. Activate local directory /storage/emulated/0/WhatsApp for auto-upload in Nextcloud App

### Expected behaviour
- Backup files automatically uploaded to Nextcloud server overwriting old (and outdated) backups

### Actual behaviour
- Upload fails with sync conflict that needs to be resolved manually for each individual file.

### Can you reproduce this problem on https://try.nextcloud.com?
- Yes

### Environment data
Android version:
10
Device model: 
Samsung s9 Plus
Stock or customized system:
Stock
Nextcloud app version:
3.11.0
Nextcloud server version:
18.0.0.3
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by fodinabor**
Resolves #5827
Fix #5755 
Fix #5599
Fix #4260
Fix https://github.com/nextcloud/android/issues/5846

Since #4788 synching WhatsApp Backups or similar files that don't change their name to Nextcloud is horrible, as one is asked how the files should be handled for every single file every day (well - as often the files change..).

This PR adds the option for synced folders how name collisions with updated files should be handled.
The options are (as proposed in #5599):
- Ask me every time
- Rename new version
- Overwrite remote version

image

Disclaimer: probably did not run all tests cleanly and did not update the screenshots, as that seemed nearly impossible on Windows..

### CODE REVIEW

File: src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java [hunk 1]
```diff
@@ -167,6 +167,7 @@ private SyncedFolderDisplayItem create(String folderName, boolean enabled) {
                                            true,
                                            "test@nextcloud.com",
                                            1,
+                                           3,
```
[the remark this answers is not in the document]
Comment (fodinabor) [reply src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java]: Fixed.

File: src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java [hunk 2]
```diff
@@ -146,6 +151,33 @@ public void setUploadAction(String uploadAction) {
...
+    public Integer getNameCollisionPolicyInteger() {
+        switch (nameCollisionPolicy) {
+            case ASK_USER:
+                return 0;
+            case OVERWRITE:
+                return 1;
+            case RENAME:
+                return 2;
+        }
+        return 0;
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java:164]: Maybe move this as default in switch?

File: src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java [hunk 3]
```diff
@@ -146,6 +151,33 @@ public void setUploadAction(String uploadAction) {
...
+    }
+
+    public void setNameCollisionPolicy(String nameCollisionPolicy) {
+        switch (nameCollisionPolicy) {
+            case "NAME_COLLISION_POLICY_ASK":
+                this.nameCollisionPolicy = FileUploader.NameCollisionPolicy.ASK_USER;
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java:170]: "this," is unneeded

**Comment by tobiasKaminsky** [comment]
Welcome on board :tada: 

Some very very minor issues.
Other than that is perfect :heart:

File: src/main/java/com/owncloud/android/datamodel/SyncedFolderDisplayItem.java [hunk 4]
```diff
@@ -60,6 +60,7 @@ public SyncedFolderDisplayItem(long id,
                                    boolean subfolderByDate,
                                    String account,
                                    int uploadAction,
+                                   int nameCollisionPolicy,
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/datamodel/SyncedFolderDisplayItem.java:63]: No sure why do we pass a primitive type instead of strongly typed `enum` here?

File: src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java [hunk 5]
```diff
@@ -146,6 +151,33 @@ public void setUploadAction(String uploadAction) {
         }
     }
 
+
+    public Integer getNameCollisionPolicyInteger() {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java:155]: Please provide a javadoc for this method. The name does not tell the story. Why do we convert it to int? What is the meaning of this `int`? Constraints?

Please consider using primitive type instead of boxed type.

File: src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java [hunk 6]
```diff
@@ -146,6 +151,33 @@ public void setUploadAction(String uploadAction) {
...
+            case OVERWRITE:
+                return 1;
+            case RENAME:
+                return 2;
+        }
+        return 0;
+    }
+
+    public void setNameCollisionPolicy(String nameCollisionPolicy) {
+        switch (nameCollisionPolicy) {
```
Comment (ezaquarii) [inline src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java:168]: This conversion could be folded into `enum NameCollisionPolicy`:

`public static NameCollisionPolicy fromName(String policyName) { ... }` 

@tobiasKaminsky I think the name choosen for this concept is invalid. While here, we could rename it into `CollisionPolicyName`, so it respects english grammar rules. As it is now - it's just confusing.

File: src/main/res/values/attrs.xml [hunk 7]
```diff
@@ -11,4 +11,16 @@
...
 	</string-array>
+
+    <string-array name="pref_name_collision_policy_entries" translatable="false">
+        <item>@string/pref_instant_name_collision_policy_entries_always_ask</item>
+        <item>@string/pref_instant_name_collision_policy_entries_overwrite</item>
+        <item>@string/pref_instant_name_collision_policy_entries_rename</item>
+    </string-array>
+
+    <string-array name="pref_name_collision_policy_entryValues" translatable="false">
+        <item>NAME_COLLISION_POLICY_ASK</item>
```
Comment (ezaquarii) [inline src/main/res/values/attrs.xml:22]: Can we use the same names as in the `enum`? That makes it possible to use `NameCollisionPolicy.valueOf()` directly.

@tobiasKaminsky Given that the type has been probably misnamed, if we want to fix it it's time to do it here instead of spilling this confusing name everywhere.

**Comment by tobiasKaminsky** [comment]
> I don't like how we treat serialization/deserialization here - it's brittle and the logic is spraed into multiple points of interest.

As this is mainly c&p from the way I 🙈 handled this on other parts, I am fine to have this the same way for now, and refactor later.

File: src/main/res/values/attrs.xml (hunk 7 above)
Comment (fodinabor) [reply src/main/res/values/attrs.xml:22]: I actually don't see that this name is too wrong... because it's an enum of policies on what to do if a collision of filenames happens... so `NameCollisionPolicy` is the noun of it..

I also thought about eliminating this array but as `NameCollisionPolicy` contains `CANCEL` as well, it is not as easily usable in the UI code..

As a reminder the options in the enum are:
- RENAME,
- OVERWRITE,
- CANCEL,
- ASK_USER;

while the options that were to be added are:
- Ask everytime
- Overwrite
- Rename

File: src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java [hunk 8]
```diff
@@ -146,6 +151,33 @@ public void setUploadAction(String uploadAction) {
...
+            case "NAME_COLLISION_POLICY_ASK":
+                this.nameCollisionPolicy = FileUploader.NameCollisionPolicy.ASK_USER;
+                break;
+            case "NAME_COLLISION_POLICY_OVERWRITE":
```
[the remark this answers is not in the document]
Comment (fodinabor) [reply src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java:172]: Those are the values from the resource array.. I'm not sure whether it's considered bad practice to use `getResources().getTextArray(R.array.pref_name_collision_policy_entryValues)` in non-UI classes

**Comment by fodinabor** [comment]
I tried to make the `NameCollisionPolicy` / dialog index a bit cleaner and moved the code for this to the fragment, as the selection index to 'NameCollisionPolicy` mapping is only required in this specific dialog.

File: src/main/java/com/owncloud/android/jobs/FilesSyncJob.java [hunk 9]
```diff
@@ -187,7 +181,14 @@ private void syncFolder(
...
                 Long.toString(syncedFolder.getId()))) {
-            file = new File(path);
+            String remotePath;
+            boolean subfolderByDate;
+            Integer uploadAction;
+            FileUploader.NameCollisionPolicy nameCollisionPolicy;
+            boolean needsCharging;
+            boolean needsWifi;
+
+            File file = new File(path);
```
[the remark this answers is not in the document]
Comment (fodinabor) [reply src/main/java/com/owncloud/android/jobs/FilesSyncJob.java:191]: So .. as this build check doesn't seem to like either of these, what do you prefer?
Having the declarations inside the loop or outside?

**Comment by tobiasKaminsky** [comment]
@fodinabor I took the freedom to reformat the code a bit.
We try to have each parameter in a new line, if it fits not in one line (>120 chars).
This is the next time then way more better to read.

File: src/main/res/values/attrs.xml (hunk 7 above)
Comment (fodinabor) [reply src/main/res/values/attrs.xml]: @ezaquarii are you fine with the current version for now?

**Comment by tobiasKaminsky** [comment]
Rebased and let us merge this tomorrow :-)

File: src/main/res/values/attrs.xml (hunk 7 above)
Comment (ezaquarii) [reply src/main/res/values/attrs.xml]: ok

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you take care of the spotbug counter? ❤️

**Comment by tobiasKaminsky** [comment]
Thanks @fodinabor for this awesome contribution!

**Comment by piknew** [comment]
Will it fix the issue from #5755 **if remote file does not exist yet**? It is a case for 100% new file, eg. photo just taken, definitely not stored on remote (server) side yer. However, sync conflict is still reported by client?

**Comment by piknew** [comment]
v3.11.1 - not fixed for non-existing files. Strange as it seems to query... directory (not file). Following is apache access log when I click "conflicted file". App queries "getting remote version from server" (again, a file does not exist) and apache is reporting:

Apr 25 00:26:46 PKSERVER apache[25696]: *******:443 192.168.10.1 - "PROPFIND /remote.php/webdav/Photos/Camera/ HTTP/1.1" 207 RX:1809 TX:2068 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
Apr 25 00:26:46 PKSERVER apache[25708]: *******:443 192.168.10.1 - "PROPFIND /remote.php/webdav/Photos/Camera/ HTTP/1.1" 207 RX:1471 TX:13433 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
