### PR TITLE
Use userId for webdav search

### LINKED ISSUE #2400: 3.1.0rc1 InvalidArgumentException: Search is only supported on directories
### Actual behaviour
There are new errors in the nextcloud.log after update to 3.1.0 rc1

### Expected behaviour
No errors
 
### Steps to reproduce
1. Install rc1
2. Use it
3. look at the log

### Environment data
Android version: 8.0.0

Device model: SM-G950F

Stock or customized system: stock

Nextcloud app version:3.1.0 rc1

Nextcloud server version:Nextcloud 13.0.1

#### Web server error log
```
error.log
nothing
```
```
access.log
12.345.678.90 - Test [23/Mar/2018:20:59:45 +0000] "GET /index.php/204 HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:01 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "OPTIONS /remote.php/dav HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "SEARCH /remote.php/dav HTTP/1.1" 500 238 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:07 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1699 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 336 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 774 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3571 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.1.0 RC1"
12.345.678.90 - Test [23/Mar/2018:21:00:08 +0000] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true HTTP/1.1" 200 138 "-" "Mozilla/5.0 (Android) ownCloud-android/3.1.0 RC1"
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"9G1uvxSlDS4gSWpLOIi0","level":4,"time":"2018-03-23T21:00:07+00:00","remoteAddr":"12.345.67.89","user":"test","app":"webdav","method":"SEARCH","url":"\/remote.php\/dav","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Search is only supported on directories\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchHandler.php(75): OCA\\\\DAV\\\\Files\\\\FileSearchBackend->search(Object(SearchDAV\\\\XML\\\\BasicSearch))\\n#1 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchPlugin.php(123): SearchDAV\\\\DAV\\\\SearchHandler->handleSearchRequest(Array, Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: SearchDAV\\\\DAV\\\\SearchPlugin->searchHandler(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:SEARCH', Array)\\n#5 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/remote.php(164): require_once('\\\/home\\\/nginx\\\/dom...')\\n#9 {main}\",\"File\":\"\\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Files\\\/FileSearchBackend.php\",\"Line\":152}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0 RC1","version":"13.0.1.1"}
{"reqId":"QP7TtNPmEA4RDwF8VYrX","level":4,"time":"2018-03-23T21:00:07+00:00","remoteAddr":"12.345.67.89","user":"test","app":"webdav","method":"SEARCH","url":"\/remote.php\/dav","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Search is only supported on directories\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchHandler.php(75): OCA\\\\DAV\\\\Files\\\\FileSearchBackend->search(Object(SearchDAV\\\\XML\\\\BasicSearch))\\n#1 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/icewind\\\/searchdav\\\/src\\\/DAV\\\/SearchPlugin.php(123): SearchDAV\\\\DAV\\\\SearchHandler->handleSearchRequest(Array, Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: SearchDAV\\\\DAV\\\\SearchPlugin->searchHandler(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:SEARCH', Array)\\n#5 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/remote.php(164): require_once('\\\/home\\\/nginx\\\/dom...')\\n#9 {main}\",\"File\":\"\\\/home\\\/nginx\\\/domains\\\/domain.com\\\/public\\\/apps\\\/dav\\\/lib\\\/Files\\\/FileSearchBackend.php\",\"Line\":152}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.1.0 RC1","version":"13.0.1.1"}
```

```
```
InvalidArgumentException: Search is only supported on directories

    /home/nginx/domains/domain.com/public/3rdparty/icewind/searchdav/src/DAV/SearchHandler.php - line 75: OCA\DAV\Files\FileSearchBackend->search(Object(SearchDAV\XML\BasicSearch))
    /home/nginx/domains/domain.com/public/3rdparty/icewind/searchdav/src/DAV/SearchPlugin.php - line 123: SearchDAV\DAV\SearchHandler->handleSearchRequest(Array, Object(Sabre\HTTP\Response))
    [internal function] SearchDAV\DAV\SearchPlugin->searchHandler(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/nginx/domains/domain.com/public/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /home/nginx/domains/domain.com/public/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method SEARCH', Array)
    /home/nginx/domains/domain.com/public/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/nginx/domains/domain.com/public/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
    /home/nginx/domains/domain.com/public/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
    /home/nginx/domains/domain.com/public/remote.php - line 164: require_once('/home/nginx/dom...')
    {main}
```

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #2400 
* [x] Needs https://github.com/nextcloud/android-library/pull/141

We have two different things:
- loginname (username in our app): 
	- this is what you use to authenticate with, eg. on web ui or very first login on android app
	- it is used for re-authenticate once our token is expired
	- it can be different than userId on certain backends
- userID:
	- this is used for all new dav endpoints
	- it is a unique id for each server

The problem in #2400 was that loginname was used instead of userId.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

File: src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java [hunk 1]
```diff
@@ -1514,20 +1514,24 @@ public void run() {
...
         final RemoteOperation remoteOperation;
         if (!currentSearchType.equals(SearchType.SHARED_FILTER)) {
             boolean searchOnlyFolders = false;
             if (getArguments() != null && getArguments().getBoolean(ARG_SEARCH_ONLY_FOLDER, false)) {
                 searchOnlyFolders = true;
             }
 
-            remoteOperation = new SearchOperation(event.getSearchQuery(), event.getSearchType(), searchOnlyFolders);
+            String userId = AccountManager.get(MainApp.getAppContext()).getUserData(currentAccount,
+                    com.owncloud.android.lib.common.accounts.AccountUtils.Constants.KEY_USER_ID);
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java]: Is there already a constant within the class or what is the reason for using the full package descriptor?

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java]: C&P from the original code, I will have a look :-)

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java]: Yes, at line 
https://github.com/nextcloud/android/pull/2501/files/a52b75eeed7182319ef7e645136f141b7eb9aa51#diff-a76a7c99598d82da114ff289c2498fdeR1517

there is also AccountUtils used, but this is then in com.owncloud.android.authentication.

**Comment by AndyScherzinger** [comment]
:+1: looks good

@mario @ardevd please review since this PR is needed to fix the master build (which refers to the latest lib master which breaks the API for search which gets fixed by this PR) :smiley:

**Comment by mario** [comment]
👍
