### PR TITLE
AuthenticatorActivity: show dialog only if not suspended

### LINKED ISSUE #3561: [3.5.0RC2] IllegalStateException via AuthenticatorActivity.checkBasicAuthorization
GPlay:
```
java.lang.IllegalStateException: 
  at androidx.fragment.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2080)
  at androidx.fragment.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:2106)
  at androidx.fragment.app.BackStackRecord.commitInternal (BackStackRecord.java:683)
  at androidx.fragment.app.BackStackRecord.commit (BackStackRecord.java:637)
  at androidx.fragment.app.DialogFragment.show (DialogFragment.java:144)
  at com.owncloud.android.authentication.AuthenticatorActivity.checkBasicAuthorization (AuthenticatorActivity.java:1307)
  at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish (AuthenticatorActivity.java:1480)
  at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish (AuthenticatorActivity.java:1381)
  at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0 (OperationsService.java:748)
  at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run (Unknown Source:6)
  at android.os.Handler.handleCallback (Handler.java:789)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:251)
  at android.app.ActivityThread.main (ActivityThread.java:6589)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
```

### LINKED ISSUE #3651: "No network connection"
I upgraded my Nextcloud install from 15.0.2 to 15.0.4, and my Android app broke.  All uploads failed.  I logged out, but couldn't log back in, it just says "No network connection.". Uninstalled and reinstalled (v3.5.0), but got the same error.

Uninstalled and downgraded to 3.4.2, but that's also giving me the same error now.

Both versions were working prior to upgrading the server.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #3561

This is trying to fix it. Basically you are not allowed to show a dialog after suspending an activity, as on resume Android cannot restore this dialog and as this is bad UX, they chose to refuse it.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 Don't see a nice(r) way of preventing this at the moment

File: src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java [hunk 1]
```diff
@@ -1305,9 +1312,11 @@ private void checkBasicAuthorization(@Nullable String webViewUsername, @Nullable
...
 
         /// be gentle with the user
-        IndeterminateProgressDialog dialog =
-                IndeterminateProgressDialog.newInstance(R.string.auth_trying_to_login, true);
-        dialog.show(getSupportFragmentManager(), WAIT_DIALOG_TAG);
+        if (!suspended) {
+            IndeterminateProgressDialog dialog = IndeterminateProgressDialog.newInstance(R.string.auth_trying_to_login,
+                                                                                         true);
+            dialog.show(getSupportFragmentManager(), WAIT_DIALOG_TAG);
+        }
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java]: It might also be worth a try to check if this could work:
```
    FragmentManager fm = getSupportFragmentManager();
    IndeterminateProgressDialog dialog  = new IndeterminateProgressDialog();
    // dialog .show(getSupportFragmentManager(), WAIT_DIALOG_TAG);
    FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
    ft.add(dialog , WAIT_DIALOG_TAG);
    ft.commitAllowingStateLoss();
```

Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java]: This should be the fix whole I can't say if it works in this case since I remembered this solution and Googled it.

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java]: Then I'll try your way :-)

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java]: Updated
