### PR TITLE
Fix crashes during scheme normalization on login

### LINKED ISSUE #9338: Problem logging in with server address in `ip:port` format
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate
Screenshot_2021-11-21-14-26-29-144_com nextcloud client

### LINKED ISSUE #9365: Login crashes when server URL contains invalid characters
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by AlvaroBrey**
We can't check this with `URI` because `URI.create` will crash with an `IllegalArgumentException` if there is a host and port but no scheme (for example: `127.0.0.1:8080`).
The workaround is to manually check for scheme and just skip URI creation if not present.

Fixes #9338
Fixes #9365
Follow up to #8535

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]

File: src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java [hunk 1]
```diff
@@ -771,7 +771,12 @@ private void checkOcServer() {
                 accountSetupBinding.hostUrlInput.setText(uri);
             }
 
-            uri = AuthenticatorUrlUtils.normalizeScheme(uri);
+            try {
+                uri = AuthenticatorUrlUtils.normalizeScheme(uri);
+            } catch (IllegalArgumentException ex) {
+                // Let Owncloud library check the error of the malformed URI
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java:777]: Nextcloud library 🙈

Comment (AlvaroBrey) [reply src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java]: Fixed, was c&p from somehwere else
