### PR TITLE
Reduce number of calls to /index.php/204 if there is nothing to do.

### LINKED ISSUE #2263: Too many queries in the background?
### Actual behaviour

The app fires so many queries to the status.php and /index.php/204 that my apache's mod_evasive blocks it. This happens in the background, when the app isn't in use, even at nights. ~BUT this only seems to happen when my smartphone is connected via cellular networks, NOT when connected via WLAN.~

### Expected behaviour
- Less queries
 
### Steps to reproduce
1. Connect smartphone ~via cellular network (LTE, HSDPA)~
2. Let app run in background

### Environment data
Android version: 7.1.2

Device model: Oneplus One

Stock or customized system: Custom: Lineage OS (Sultanxda)

Nextcloud app version: 3.0.2

Nextcloud server version: 13.0.0.14

#### Access log:

	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 4616 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 4616 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 1635 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:30:58 +0100] "GET /status.php HTTP/1.1" 200 1637 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:00 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1633 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1627 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1627 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 4610 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 4614 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 4616 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1578 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1629 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1572 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1574 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1574 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 200 1633 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40332 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1580 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /status.php HTTP/1.1" 302 1568 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /status.php HTTP/1.1" 200 1629 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:01 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40330 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /status.php HTTP/1.1" 302 1574 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40338 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /status.php HTTP/1.1" 200 1631 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40340 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40330 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"
	<server-ip>:443 <smartphone-ip> [01/Mar/2018:10:31:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 200 40334 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.2"

#### Nextcloud log (data/nextcloud.log)
 ( only some Trusted domain errors in this timeframe)

### EDIT: 
Sometimes it's status.php, some times index.php

### EDIT2: 
nvmd, affects WLAN networks as well, just less often.

### EDIT3: 
screw this issue report, now it's only /index.php/204

### PR DESCRIPTION
**Pull request by tomaszduda23**
Resolves #2263

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

File: src/main/java/com/owncloud/android/operations/UploadFileOperation.java [hunk 1]
```diff
@@ -715,6 +710,11 @@ private RemoteOperationResult checkConditions(File originalFile) {
             remoteOperationResult =  new RemoteOperationResult(ResultCode.DELAYED_IN_POWER_SAVE_MODE);
         }
 
+        // check that internet is not behind walled garden
+        if (!connectivityService.getConnectivity().isConnected() || connectivityService.isInternetWalled()) {
+            remoteOperationResult =  new RemoteOperationResult(ResultCode.NO_NETWORK_CONNECTION);
+        }
+
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/operations/UploadFileOperation.java:717]: Good idea, but then we should move this to the end, as it is the most expensive operation.
All other (metered wifi, battery, power saving, file exists) can be done locally

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Thanks, this will help a lot to prevent unneeded checks! :tada:
