### PR TITLE
Show nice error message instead of crash via exception

### LINKED ISSUE #1456: 2.0RC5:   java.lang.IllegalStateException - com.owncloud.android.ui.preview.PreviewImageFragment.onActivityCreated
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2762)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2848)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1552)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6334)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
Caused by: java.lang.IllegalStateException: 
  at com.owncloud.android.ui.preview.PreviewImageFragment.onActivityCreated (PreviewImageFragment.java:225)
  at android.support.v4.app.Fragment.performActivityCreated (Fragment.java:2257)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1367)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1569)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1636)
  at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated (FragmentManager.java:2977)
  at android.support.v4.app.FragmentController.dispatchActivityCreated (FragmentController.java:192)
  at android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:603)
  at android.support.v7.app.AppCompatActivity.onStart (AppCompatActivity.java:178)
  at com.owncloud.android.ui.activity.BaseActivity.onStart (BaseActivity.java:189)
  at com.owncloud.android.ui.activity.DrawerActivity.onStart (DrawerActivity.java:1273)
  at com.owncloud.android.ui.activity.FileActivity.onStart (FileActivity.java:188)
  at com.owncloud.android.ui.preview.PreviewImageActivity.onStart (PreviewImageActivity.java:173)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1322)
  at android.app.Activity.performStart (Activity.java:6760)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2725)
```

### PR DESCRIPTION
**Pull request by AndyScherzinger**
resolves #1456 

...showing a nice error message instead of throwing an exception which leads to an app crash:
device-2017-09-06-164450

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario please review,, this is another 2.0.0 fix - for #1456, see screenshot above.

This can be tested via debugger:
* set a break point in ```PreviewImageFragment.onStart()```
* manipulate ```mFile``` and set its variable ```mLocalPath``` to ```null```

This will lead to ```isDown()``` to be false and thus show the error message.

**Comment by mario** [comment]
👍

File: src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java [hunk 1]
```diff
@@ -236,19 +230,17 @@ public void onSaveInstanceState(Bundle outState) {
...
     }
 
-
     @Override
     public void onStart() {
         super.onStart();
-        if (getFile() != null) {
+        if (getFile() != null && !getFile().isDown()) {
+            showErrorMessage(R.string.preview_image_error_no_local_file);
+        } else if (getFile() != null) {
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java]: This can be simplified to:

```
if (getFile() == null || !getFile().isDown()) { 
    showErrorMessage(R.string.preview_image_error_no_local_file);
} else {
    // loading task
}
```

Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java]: Nice catch, fixed via https://github.com/nextcloud/android/pull/1500/commits/6a8a0f7c75baa26a3303c89629b09e91d2c361e0

**Comment by tobiasKaminsky** [comment]
:+1: 
Now the question is...code was changed, so ideally mario has to re-check, but pull aprove would also allow me to merge directly.

**Comment by AndyScherzinger** [comment]
At least let's wait until drone finishes the build + checks

**Comment by mario** [comment]
Merge
