### PR TITLE
Iteration 2 for file detail & new sharing 

### LINKED ISSUE #2610: #2573 breaks account change
the account switch isn't working anymore at all on the PR/branch #2573

Simply try to switch the account (2 accounts on 2 different servers).
If you remove the launch singleTop flag it works again for the user list in the drawer but still doesn't work at all for the avatar clicks in the drawer header. So something is really broken here.

Good thing, this doesn't happen on the master branch, or trashbin branch thus it must have been introduced via #2573

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Iteration 1 can be found here: #2533 :ballot_box_with_check: 

WiP for #2485 and collab with @tobiasKaminsky

* [x] use butterknife for view binding
* [x] remove file type icon for non-preview-able files
* [x] support editing/deletion of existing sharees
* [x] support for expiration date
* [x] support adding new/further sharees
* [x] support sharing via link
* [x] add fetching of sharee avatars
* [x] fallback theming for checkable menu items
* [x] FIX #2610 :exclamation: 
* [x] replace `ListView`with `RecyclerView`

**Open for iteration 3/4**
* [ ] implement actual email share type menu options (behaves as is, so atm like a user share type)
* [ ] remove old/legacy ShareActivity and launch FileDetailFragment with sharing tab active
* [ ] MVP the sharing part

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Some theming bug:

**Comment by tobiasKaminsky** [comment]
Current state:
 
 


This really looks great, @AndyScherzinger :tada:

Some observations:
- currently the timestamp seems to be absolute all the time, shall we also use relative timestamps there?
- send/share in overflow should be replaced by "send (to other apps)" only as share (via link / with another nc user) is done in the sharing tab.
- send/share should be named "share"

**Comment by AndyScherzinger** [comment]
> * currently the timestamp seems to be absolute all the time, shall we also use relative timestamps there?

The webUI always shows a relative timestamp, not sure this makes sense since > 1year ago doesn't help. I didn't change the timestamp display. So also the old details view showed the absolute timestamp simply as the files meta info. I am fine either way and we could use the Android app's relative timestamp which switches to absolute timestamps for very older files and would be consistent with the file list view.

> * send/share in overflow should be replaced by "send (to other apps)" only as share (via link / with another nc user) is done in the sharing tab.
> * send/share should be named "share"

I am a bit confused. Rename send/share to "send (to other apps)" or to "share"?

Nice catch with the theming bug while I'd expect this to be present in the actual master already even before we started to rewrite the details screen, no?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky correction, action bar coloring bug has been introduced by me :/

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I fixed the theming issue :)

**Comment by tobiasKaminsky** [comment]
>  we could use the Android app's relative timestamp which switches to absolute timestamps for very old files and would be consistent with the file list view in the Android app.

Yes, please let us change :-)

>>- send/share in overflow should be replaced by "send (to other apps)" only as share (via link / with another nc user) is done in the sharing tab.
>>- send/share should be named "share"

>I am a bit confused. Rename send/share to "send (to other apps)" or to "share"?

Current "send/share" in overflow menu should become "send" and directly open the app chooser as bottom page, without "send / link":
image

This is not yet possible, but should be easy to hide both "share" / "link" buttons.


This "send/share" text should be "Share" as it is only share: share by link, share with users/groups/emails.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky fixed using relative timestamps and also did the renaming you mentioned while also moving to a distinct menu xml file.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I also implemented the part you mentioned with send:
> This is not yet possible, but should be easy to hide both "share" / "link" buttons.

File: src/main/java/com/owncloud/android/ui/TextDrawable.java [hunk 1]
```diff
@@ -97,25 +97,37 @@ public TextDrawable(String text, int r, int g, int b, float radius) {
...
      * @param name       the name
      * @param radiusInDp the circle's radius
      * @return the avatar as a TextDrawable
-     * @throws UnsupportedEncodingException if the charset is not supported when calculating the color values
-     * @throws NoSuchAlgorithmException     if the specified algorithm is not available when calculating the color values
      */
     @NonNull
-    public static TextDrawable createNamedAvatar(String name, float radiusInDp) throws
-            UnsupportedEncodingException, NoSuchAlgorithmException {
+    public static TextDrawable createNamedAvatar(String name, float radiusInDp) {
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/ui/TextDrawable.java]: @tobiasKaminsky why did you remove the exceptions? I thought UnsupportedEncodingException, NoSuchAlgorithmException can be thrown if color calculation fails?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky need further input...

> Sharing to a new user/group/link:
> * click on text input on share tab hides activity/sharing toggle to have more space for actually searching
Disagree on this since I am not sure hiding can be done easily and second most important point: when would you show it again? On focus lost? User chosen? This makes the UI jumpy and I don't think this is a good idea
> * share link as entry beneath search field
>   * with "can edit"
>   * click on it opens up existing app chooser to receive link
Simply having to ask why, how, what?! Link isn't simply "link" + "can edit". It is also:
* password protect (plus password field)
* set expiration date (plus date filed/picker)

All this (even the the webUI) is shown when set and is currently also shown when looking at the existing share dialog... Looking at the web the link part is put below the user/group/email list simply because, well, web got to much space to fill while we don't... So putting all this below the search field doesn't make any sense while putting all link stuff above doesn't make sense either. Only thing I can come up with right away would be to differ from the webUI and have 2 separate tabs, one for NC sharing and one for link, while finding proper names seems tricky. Best would then probably be "Sharing" and "Link" (I know link is also a form of sharing while the actual sharing is done separately by the user not the app/server, so I'd be fine with that)

cc @jancborchardt since you came up with the overall redesign of the details screen.

File: src/main/java/com/owncloud/android/ui/TextDrawable.java (hunk 1 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/TextDrawable.java]: Right, now I see it. 
I also did not removed it, but this was AndroidStudio and then I just removed the other try/catch blocks.
--> we need to revert this.

**Comment by tobiasKaminsky** [comment]
> Disagree on this since I am not sure hiding can be done easily and second most important point: when would you show it again? On focus lost? User chosen? This makes the UI jumpy and I don't think this is a good idea

I would say, when you click "back" arrow.
But this is something we can discuss for iteration 3 or so. For now I would leave it this way.

Regarding link:
If there is none link yet, show "add link" with "can edit" as checkbox.
Clicking on this will create the link and opens it as "send / app chooser".

For any existing link, it should have an option button (three dots), where the additional settings can be done, also deletion of the link.

Jan's idea was to have it as quick as possible to share via link. The not so often needed options should be sane defaults and be hidden.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky also a way to go and fine with me. So how would the other information then be presented to the user? Show link details in a Dialog? If setup with all the extra information will it then still be hiden since it takes to much space and then also only be shown with let's say a menu entry "Details" in the link's 3-dor menu?

**Comment by jancborchardt** [comment]
Nice nice, looks very good! :)

From first look only one thing is a bit off: The whole block with »Send/share«, »Share by link enabled« and »Users and groups with access«. It seems it would be much simpler to cut that whole block, and instead in the list of Sharees on the right show the checkbox with »edit« (or »can edit« if not too long) to signify what the people can do.

**Comment by AndyScherzinger** [comment]
@jancborchardt  thanks for the feedback :smiley: 

> in the list of Sharees on the right show the checkbox with »edit« (or »can edit« if not too long) to signify what the people can do.

We can do that, sure, while we might run into very ellipsized names then since the space on a phone is rather limited, especially on low-end devices, but worth a try.

> (And of course sort the people with most rights first.)

We haven't started with sorting (yet), but yeah, makes sense :)

@jancborchardt Also, referring to my comment https://github.com/nextcloud/android/pull/2573#issuecomment-389133797 how would you display the additional settings of a link? Just asking since putting it into an extra dialog to either configure or if configured to show this information leads to some further clicks (which is of course fine if we agree on doing so).

**Comment by jancborchardt** [comment]
> we might run into very ellipsized names then since the space on a phone is rather limited, especially on low-end devices, but worth a try.

Below a certain limit we could omit the »can edit« part then? But on most standard phones there should be enough space to show it while still being able to read most of many names.


The additional settings of a link should be in a 3-dot-menu of that row, same as for the user shares. That way it’s all consistent.

**Comment by AndyScherzinger** [comment]
> The additional settings of a link should be in a 3-dot-menu of that row, same as for the user shares. That way it’s all consistent.

This can't be the case since the 3-dot icon opens a menu and showing a expiration date or that a password is set isn't a menu item and thus can't be in a menu. So for the link you would have to open a dialog thus not consistent with share user names and also due to this can't be consistent. 

Can we please get to the point (while I have no idea how to get there) where we do not have to explain the Android platform all the time? Sorry but I am feeling pushed to raise this again but having to explain the Android platform/UI in many cases is just wrong and energy draining and shouldn't be necessary.

**Comment by jancborchardt** [comment]
> This can't be the case since the 3-dot icon opens a menu and showing a expiration date or that a password is set isn't a menu item and thus can't be in a menu. So for the link you would have to open a dialog thus not consistent with share user names and also due to this can't be consistent.

Sorry, let me be more exact: Of course there should not be an input field for a password or a calendar for the expiration date in that menu. The menu should look like:

- Permissions: Allow editing (/ Read-only / Upload only)
- Password protect (/ Password-protected)
- Set expiration date (/ Expires in 2 days)

So it would show the current status quickly, and when you want to change it you click on the menu entry. For permissions it opens a modal, for password it opens a modal with input, for expiration date it opens a calendar.


> Sorry but I am feeling pushed to raise this again but having to explain the Android platform/UI in many cases is just wrong and energy draining and shouldn't be necessary.

Sorry about that. I have the feeling this often occurs because I say »just like in (or similar to) the web interface«. When I say that I do not mean that it should be _exactly_ like in the web interface, but only roughly layout- and interaction-wise – basically taking the web interface as if it was a mockup. Of course the general feel should be Android-y, and you are the experts there. :) And then we discuss on that basis what has to be different.

**Comment by tobiasKaminsky** [comment]
For [reference](https://developer.android.com/guide/topics/search/search-dialog):
> The second scenario using "singleTop" launch mode is usually ideal, because chances are good that once a search is done, the user will perform additional searches and it's a bad experience if your application creates multiple instances of the searchable activity. So, we recommend that you set your searchable activity to "singleTop" launch mode in the application manifest.

**Comment by AndyScherzinger** [comment]
NPE Bug, when downloading a file (just clicking on a not downloaded video in the OCFIleLIstFragment):
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment.lambda$fetchAndSetData$4$FileDetailActivitiesFragment(FileDetailActivitiesFragment.java:258)
        at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$$Lambda$2.run(Unknown Source:24)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by tobiasKaminsky** [comment]
Additionally I found:
- go into file detail, remove a file local only -> shows file listing
- click on a non-downloaded text file in file listing -> crashing

All seem to be related that 
https://github.com/nextcloud/android/blob/d3fb5d91ded6073320ad56fa127044de993d0c16/src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java#L240-L243

swipeEmptyListRefreshLayout is null.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky 
> go into file detail, remove a file local only -> shows file listing

This is as-is functionality and has always been like that, see master:
https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L1678

Whenever a delete operation result is received by the activity it'll remove the second fragment (the detail fragment). Unfortunately the clean method is used in many places and if we want to change this behavior in this one case then we should do this in another PR imho.

PS: Rebased the branch due to issues with the search operation changes and compile errors.

**Comment by mario** [comment]
@AndyScherzinger let me know when ready to review.

**Comment by AndyScherzinger** [comment]
@mario well, now that I fixed the latest lint issues I'd say the PR is ready to review, the remaining changes I mentioned in the issue description should imho go into (yet another file details) PR so that this PR doesn't grow any further except for fixes due to found bug / review comments. 
Appreciate your help and feedback, same goes for @tobiasKaminsky and @ardevd of course. Looking forward to your comments.

**Comment by AndyScherzinger** [comment]
Screenshots for @jancborchardt for design check
device-2018-05-23-001348

device-2018-05-23-001413

device-2018-05-23-001442

@jancborchardt please be aware that I slightly differed
* from your recommendation regarding editing of the permissions, since links only have max. 2 permissions (can edit, hide file listing) and can edit is always shown, I just put hide file listing in the file menu instead of having a pop-up with 1 permission to dis-/enable
* I haven't renamed the hide file listing yet (probably for a later iteration)
* the link part is more or less a refreshed UI for the existing functionality of the Android client, thus it only supports setting "can edit" for folders, not for files (probably for a later iteration)
* UX issue: the menu isn't hidden as isn't can edit which will lead to a server error since the link hasn't been shared (isn't "active") also likely for a later iteration
* clicking on the share icon in the file listing doesn't yet open the new, revamped details screen with the sharing tab being active, except for folders (where it was easy) - (probably for a later iteration)

The reason for all the "probably for a later iteration" attributions is that the PR is already quite large just to get links and sharees working at all, so fine tuning should be done in the next iteration of the feature (hopefully right after the merge) especially since that will again mean a larger amount of code changes which makes it hard for the code reviews. So that is the trade off, also rebases already start to get more complicated...

File: src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java [hunk 2]
```diff
@@ -1723,6 +1807,120 @@ private void onMoveFileOperationFinish(MoveFileOperation operation,
...
+            String username;
+            try {
+                OwnCloudAccount oca = new OwnCloudAccount(getAccount(), this);
+                if (oca.getDisplayName() != null && !oca.getDisplayName().isEmpty()) {
+                    username = oca.getDisplayName();
+                } else {
+                    username = AccountUtils.getUsernameForAccount(getAccount());
+                }
+            } catch (Exception e) {
+                username = AccountUtils.getUsernameForAccount(getAccount());
```
Comment (tobiasKaminsky) [inline src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java]: Do we really want to have the username (which is just using part before @ --> loginname).
If we want to have the unique userid, we can use:
`
accountManager.getUserData(account,
                        com.owncloud.android.lib.common.accounts.AccountUtils.Constants.KEY_USER_ID);
`

Loginname/username (on android): what you use for first time to authenticate, can be "userId, email/some other fancy stuff, especially when using LDAP).
userid: unique id per instance, which identifies an user

Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java]: It is just a refactoring yes while I am fine if we want to change that while I'd be happy if you could take care of that since I am not sure what I'd need to do exactly.

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java]: I will do this after 3.2 in another PR, globally for the app, so that this PR does not get bigger ;-)

**Comment by AndyScherzinger** [comment]
**This PR breaks the account swicthing, so do not merge!**

Details can be found here: #2610

**Comment by AndyScherzinger** [comment]
rebased to resolve conflicts

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky @ardevd iteration 2 of the details screen is ready to review, some stuff is left for iteration 3 & 4

**Comment by AndyScherzinger** [comment]
@jancborchardt @nextcloud/designers here are the screenshots of iteration 2 of the new file details screen which implements the first set of functionality, more to follow in iteration 3.

device-2018-05-27-153553
device-2018-05-27-153731
device-2018-05-27-153528

As mentioned earlier 
* having the "can edit" shown on each row will come with iteration 3
* same applies for menu entries for mail shares and completely removing the old sharing views

**Comment by AndyScherzinger** [comment]
Also please ignore the menu texts... they have been changed but my client shows EN_GB due to its locale and that on isn't translated since the PR hasn't been merged yet!

**Comment by AndyScherzinger** [comment]
Updated Screenshots

device-2018-05-27-215054
device-2018-05-27-214907
device-2018-05-27-214940

**Comment by AndyScherzinger** [comment]
Shortened the edit label to the shortest version @jancborchardt mentioned:
device-2018-05-27-221638

**Comment by AndyScherzinger** [comment]
@jancborchardt @nextcloud/designers please review

**Comment by AndyScherzinger** [comment]
Here are screenshot of "the worst it can get" mdpi device at 320x480, so mail is I'd say still okay + plus we support landscape

device-2018-05-27-222712
device-2018-05-27-222701

**Comment by tobiasKaminsky** [comment]
BUG:
- open up detail view
- share a file/folder via link (1st time)
- press back
- bug#1: sharing is not shown in file list
- open detail view
- sharing link is not enabled

**Comment by AndyScherzinger** [comment]
List frefresh bug has been fixed via https://github.com/nextcloud/android/pull/2573/commits/5a6f4933a611161f45a2e20528c85ed6ff3ceab9

**Comment by tobiasKaminsky** [comment]
On next iteration we can enhance landscape mode on smaller phones:


Functionwise it is working :tada: 
Next step: code review

**Comment by tobiasKaminsky** [comment]
:+1: 
CR: done
There are general points we can tackle in future
- try to use / agree on a code style
```
((FileActivity) getActivity()).getFileOperationsHelper().
￼                setPermissionsToShare(
￼                        share,
￼                        permissions
￼                )
￼        ;
```
This in my opinion, very ugly and could be nicer:
```
((FileActivity) getActivity()).getFileOperationsHelper().
￼                setPermissionsToShare(share, permissions);
```

- currently we have still some duplicate sipeRefreshListener, depends if view is empty or filled. This can be replaced via https://github.com/nextcloud/android/blob/b67e6065198e5f26f188cf642a98670734e5c7bb/src/main/java/com/owncloud/android/ui/EmptyRecyclerView.java#L35

- agree on code documentation

But as said, this is not only in this PR, but an overall observation.

**Comment by AndyScherzinger** [comment]
Thanks @tobiasKaminsky 

as for the coding style... not sure how that'll work out for more complex scenarios like:
```
FileDetailSharingFragmentHelper.setupHideFileListingMenuItem(
                menu.findItem(R.id.action_share_link_hide_file_listing),
                file.isFolder(),
                shareByLinkAllowEditing.isChecked(),
                publicShare.getPermissions()
        );
```

**Comment by AndyScherzinger** [comment]
> currently we have still some duplicate sipeRefreshListener, depends if view is empty or filled. This can be replaced via ...

Good point and yeah, let's do that in iteration 3

**Comment by AndyScherzinger** [comment]
@ardevd @mario can you please review, this PR needs to go into RC1 :)

Any comments @jancborchardt? :)

**Comment by jancborchardt** [comment]
Really great work again! :) Only some small design details:
- The text of the search field and the »Share link« should be left-aligned the same as the names below it. So both need to move a bit to the right
- »Share link« should be the same font size as the names
- In general, how many different font sizes are in this view? Basically everything should be the same size
- Let’s make the file name bold to emphasize, otherwise it drowns a bit
- Does »ACTIVITIES« and »SHARING« need to be all-caps? Also, does the currently active one have slightly larger font-size? (If this is all conform with Android guidelines, nevermind :)
- In the additional options, the wording for expiration date and password can be improved:
   - When there is no expiration date set, it should say: »Set expiration date«, and when there is one set, say »Expires 30 October 2018« (or whatever date)
   - When there is no password set, say »Set password« and when there is a password set, say »Password-protected«

That’s all for now. :) More we can see once we really use it in the beta.

**Comment by AndyScherzinger** [comment]
@jancborchardt see my comments
> - The text of the search field and the »Share link« should be left-aligned the same as the names below it. So both need to move a bit to the right

see my comment https://github.com/nextcloud/android/pull/2573#issuecomment-392554348

> - »Share link« should be the same font size as the names

DONE

> - In general, how many different font sizes are in this view? Basically everything should be the same size

There were 2 actually (14sp, 16sp), now just one - DONE

> - Let’s make the file name bold to emphasize, otherwise it drowns a bit

DONE

> - Does »ACTIVITIES« and »SHARING« need to be all-caps? Also, does the currently active one have 
slightly larger font-size? (If this is all conform with Android guidelines, nevermind :)

DONE

> - In the additional options, the wording for expiration date and password can be improved:
   - When there is no expiration date set, it should say: »Set expiration date«, and when there is one set, say »Expires 30 October 2018« (or whatever date)
   - When there is no password set, say »Set password« and when there is a password set, say »Password-protected«

DONE

**Comment by jancborchardt** [comment]
Great stuff!

Regarding the search and checkbox – if it's fixed together by Android then those parts look better like they were before. :/

And one more thing: Can you increase the font size of only the file name a bit? So that it's the size of the header text font. (Or compare to Google Play store app view, which is very similar to this view.)

**Comment by AndyScherzinger** [comment]
All DONE and rebased, ready for final approval/review @tobiasKaminsky @mario @ardevd

File: src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java [hunk 3]
```diff
@@ -839,13 +840,14 @@ private int getAvatarDimension(){
...
-            String username = mUsername;
 
-            ArbitraryDataProvider arbitraryDataProvider = new ArbitraryDataProvider(
-                    MainApp.getAppContext().getContentResolver());
+            String accountName = mUserId + "@" + mServerName;
+
+            ArbitraryDataProvider arbitraryDataProvider = new ArbitraryDataProvider(mContext.getContentResolver());
+
+            String eTag = arbitraryDataProvider.getValue(accountName, ThumbnailsCacheManager.AVATAR);
+            String avatarKey = "a_" + mUserId + "_" + mServerName + "_" + eTag;
```
Comment (mario) [inline src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java]: Because I don't and don't wanna know what "a" is, please change to "avatar".

File: src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java [hunk 4]
```diff
@@ -877,18 +874,19 @@ Drawable doAvatarInBackground() {
...
 
                                 Bitmap bitmap = BitmapFactory.decodeStream(inputStream);
                                 avatar = ThumbnailUtils.extractThumbnail(bitmap, px, px);
 
                                 // Add avatar to cache
-                                if (avatar != null) {
+                                if (avatar != null && !TextUtils.isEmpty(newETag)) {
                                     avatar = handlePNG(avatar, px, px);
-                                    String newImageKey = "a_" + username + "_" + eTag;
+                                    String newImageKey = "a_" + mUserId + "_" + mServerName + "_" + newETag;
```
Comment (mario) [inline src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java]: avatar_ instead of a_.

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java [hunk 5]
```diff
@@ -156,97 +157,35 @@ public static void hideMenuItems(MenuItem... items) {
...
+        filterFavorite(toShow, toHide, synchronizing);
+        filterUnfavorite(toShow, toHide, synchronizing);
+        filterEncrypt(toShow, toHide, endToEndEncryptionEnabled);
+        filterUnsetEncrypted(toShow, toHide, endToEndEncryptionEnabled);
+        filterSetPictureAs(toShow, toHide);
+    }
 
-        // SHARE FILE
+    private void filterShareFile(List<Integer> toShow, List<Integer> toHide, OCCapability capability) {
         boolean shareViaLinkAllowed = (mContext != null &&
```
Comment (mario) [inline src/main/java/com/owncloud/android/files/FileMenuFilter.java]: Useless variable. I already removed them in a private branch, but please remove them as they bring nothing. Just use their content in the one place where needed. I know it's not related to this PR, but you touch the file so :P

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java [hunk 6]
```diff
@@ -156,97 +157,35 @@ public static void hideMenuItems(MenuItem... items) {
...
                 mContext.getResources().getBoolean(R.bool.share_via_link_feature));
         boolean shareWithUsersAllowed = (mContext != null &&
```
Comment (mario) [inline src/main/java/com/owncloud/android/files/FileMenuFilter.java]: Same as above.

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java [hunk 7]
```diff
@@ -156,97 +157,35 @@ public static void hideMenuItems(MenuItem... items) {
...
                 mContext.getResources().getBoolean(R.bool.share_with_users_feature));
 
-        OCCapability capability = mComponentsGetter.getStorageManager().getCapability(mAccount.name);
         boolean shareApiEnabled = capability != null &&
```
Comment (mario) [inline src/main/java/com/owncloud/android/files/FileMenuFilter.java]: Same.

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java [hunk 8]
```diff
@@ -258,67 +197,160 @@ private void filter(List<Integer> toShow, List<Integer> toHide, boolean inSingle
         } else {
             toShow.add(R.id.action_send_share_file);
         }
+    }
 
-        // SEE DETAILS
-        if (!isSingleFile()) {
+    private void filterDetails(List<Integer> toShow, List<Integer> toHide) {
+        if (!isSingleSelection()) {
```
Comment (mario) [inline src/main/java/com/owncloud/android/files/FileMenuFilter.java]: Invert.

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java [hunk 9]
```diff
@@ -258,67 +197,160 @@ private void filter(List<Integer> toShow, List<Integer> toHide, boolean inSingle
...
             toHide.add(R.id.action_see_details);
         } else {
             toShow.add(R.id.action_see_details);
         }
+    }
 
-        // Kept available offline
+    private void filterKeepAvailableOffline(List<Integer> toShow, List<Integer> toHide, boolean synchronizing) {
         if (!allFiles() || synchronizing || allKeptAvailableOffline()) {
```
Comment (mario) [inline src/main/java/com/owncloud/android/files/FileMenuFilter.java]: And again.

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java [hunk 10]
```diff
@@ -258,67 +197,160 @@ private void filter(List<Integer> toShow, List<Integer> toHide, boolean inSingle
...
+    private void filterOpenWith(List<Integer> toShow, List<Integer> toHide, boolean synchronizing) {
+        if (!isSingleFile() || !anyFileDown() || synchronizing) {
+            toHide.add(R.id.action_open_file_with);
+        } else {
+            toShow.add(R.id.action_open_file_with);
+        }
+    }
+
+    private void filterDeselectAll(List<Integer> toShow, List<Integer> toHide, boolean inSingleFileFragment) {
+        if (!inSingleFileFragment) {
```
Comment (mario) [inline src/main/java/com/owncloud/android/files/FileMenuFilter.java]: Invert again. Positive first.

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java (hunk 5 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: which variable?

File: src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java [hunk 11]
```diff
@@ -62,27 +64,64 @@
...
 public class FileDetailFragment extends FileFragment implements OnClickListener {
+    private static final String TAG = FileDetailFragment.class.getSimpleName();
+    public static final String FTAG_CONFIRMATION = "REMOVE_CONFIRMATION_FRAGMENT";
+    public static final String FTAG_RENAME_FILE = "RENAME_FILE_FRAGMENT";
+
+    private static final String ARG_FILE = "FILE";
+    private static final String ARG_ACCOUNT = "ACCOUNT";
+    private static final String ARG_ACTIVE_TAB = "TAB";
+
+    @Nullable @BindView(R.id.fdProgressBlock)
```
Comment (mario) [inline src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java]: Kill the prefix pls.

File: src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java [hunk 12]
```diff
@@ -21,37 +21,87 @@
...
     private Account account;
+    private OCCapability capabilities;
+    private OCShare publicShare;
+
+    private Unbinder unbinder;
+
+    @BindView(R.id.searchView)
+    SearchView searchView;
+
+    @BindView(R.id.fdshareUsersList)
```
Comment (mario) [inline src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java]: fd again.

File: src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java [hunk 13]
```diff
@@ -846,7 +846,7 @@ public void onClick(View v) {
     }
 
 
-    /// BEWARE: next methods will failed with NullPointerException if called before onCreateView() finishes
+    // BEWARE: next methods will failed with NullPointerException if called before onCreateView() finishes
```
Comment (mario) [inline src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java]: "will fail" instead of "will failed".

also "next" -> "the following"

File: src/main/java/com/owncloud/android/utils/DisplayUtils.java [hunk 14]
```diff
@@ -433,50 +434,72 @@ public static SpannableStringBuilder createTextWithSpan(String text, String span
...
+        }
 
-            ArbitraryDataProvider arbitraryDataProvider = new ArbitraryDataProvider(
-                    MainApp.getAppContext().getContentResolver());
+        ArbitraryDataProvider arbitraryDataProvider = new ArbitraryDataProvider(context.getContentResolver());
 
-            String eTag = arbitraryDataProvider.getValue(account, ThumbnailsCacheManager.AVATAR);
+        String serverName = account.name.substring(account.name.lastIndexOf('@') + 1, account.name.length());
+        String eTag = arbitraryDataProvider.getValue(userId + "@" + serverName, ThumbnailsCacheManager.AVATAR);
+        String avatarKey = "a_" + userId + "_" + serverName + "_" + eTag;
```
Comment (mario) [inline src/main/java/com/owncloud/android/utils/DisplayUtils.java]: "avatar_"

File: src/main/res/drawable/divider.xml [hunk 15]
```diff
@@ -0,0 +1,31 @@
...
+        android:bottom="0dp"
+        android:left="72dp"
+        android:right="0dp"
+        android:top="0dp">
+        <shape android:shape="rectangle">
+            <solid android:color="@color/list_divider_background" />
+            <size android:height="1dp" />
+        </shape>
+    </item>
+</layer-list>
```
Comment (mario) [inline src/main/res/drawable/divider.xml]: New line.

File: src/main/res/menu/file_details_actions_menu.xml [hunk 16]
```diff
@@ -0,0 +1,99 @@
...
+      xmlns:app="http://schemas.android.com/apk/res-auto"
+      xmlns:tools="http://schemas.android.com/tools"
+      tools:ignore="AppCompatResource">
+
+    <item
+        android:id="@+id/action_rename_file"
+        android:title="@string/common_rename"
+        app:showAsAction="never"
+        android:showAsAction="never"
+        android:orderInCategory="1" />
```
Comment (mario) [inline src/main/res/menu/file_details_actions_menu.xml]: Remove orderInCategory

File: src/main/res/values/strings.xml [hunk 17]
```diff
@@ -784,4 +785,7 @@
     <string name="create_new_folder">Create new folder</string>
     <string name="uploads_view_upload_status_virus_detected">Virus detected. Upload cannot be completed!</string>
     <string name="tags">Tags</string>
+    <string name="sharee_add_failed">Adding sharee failed</string>
+    <string name="unsharing_failed">Unsharing failed</string>
+    <string name="updating_share_failed">Updateing share failed</string>
```
Comment (mario) [inline src/main/res/values/strings.xml]: Updaeting -> Updating

File: src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java (hunk 3 above)
Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java]: This is the key for our cache:
a_: avatar
t_: thumbnail
r_: resizedImage

As the key is changing for avatar, we can rename it, but then it is not consistent to the other.
Hopefully we/I find the time to change to glide, then this all will change again…

Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java]: so leave it as-is then for now?

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java (hunk 5 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/84401e73a76c71bd3efa2f9ab6ca9f54399fe1a2

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java (hunk 6 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/84401e73a76c71bd3efa2f9ab6ca9f54399fe1a2

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java (hunk 7 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/84401e73a76c71bd3efa2f9ab6ca9f54399fe1a2

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java (hunk 8 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/84401e73a76c71bd3efa2f9ab6ca9f54399fe1a2

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java (hunk 9 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: kept since it'll end up with 
```
if (allFiles() || !synchronizing || !allKeptAvailableOffline()) {
```

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java [hunk 18]
```diff
@@ -258,67 +197,160 @@ private void filter(List<Integer> toShow, List<Integer> toHide, boolean inSingle
...
         if (!allFiles() || synchronizing || allKeptAvailableOffline()) {
             toHide.add(R.id.action_keep_files_offline);
         } else {
             toShow.add(R.id.action_keep_files_offline);
         }
+    }
 
-        // Not kept available offline
+    private void filterDontKeepAvailableOffline(List<Integer> toShow, List<Integer> toHide, boolean synchronizing) {
         if (!allFiles() || synchronizing || allNotKeptAvailableOffline()) {
```
[the remark this answers is not in the document]
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: kept since it'll end up with 
```
if (allFiles() || !synchronizing || !allKeptAvailableOffline()) {
```

File: src/main/java/com/owncloud/android/files/FileMenuFilter.java (hunk 10 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/files/FileMenuFilter.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/84401e73a76c71bd3efa2f9ab6ca9f54399fe1a2

File: src/main/res/values/strings.xml (hunk 17 above)
Comment (AndyScherzinger) [reply src/main/res/values/strings.xml]: DONE via https://github.com/nextcloud/android/pull/2573/commits/c3209d817d8dccc8cc1c5c913658893e34f4ad52

File: src/main/res/menu/file_details_actions_menu.xml (hunk 16 above)
Comment (AndyScherzinger) [reply src/main/res/menu/file_details_actions_menu.xml]: DONE via https://github.com/nextcloud/android/pull/2573/commits/c3209d817d8dccc8cc1c5c913658893e34f4ad52

File: src/main/res/drawable/divider.xml (hunk 15 above)
Comment (AndyScherzinger) [reply src/main/res/drawable/divider.xml]: DONE via https://github.com/nextcloud/android/pull/2573/commits/c3209d817d8dccc8cc1c5c913658893e34f4ad52

File: src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java [hunk 19]
```diff
@@ -0,0 +1,136 @@
...
+        // do not iconify the widget; expand it by default
+        searchView.setIconifiedByDefault(false);
+
+        // avoid fullscreen with softkeyboard
+        searchView.setImeOptions(EditorInfo.IME_FLAG_NO_EXTRACT_UI);
+
+        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
+            @Override
+            public boolean onQueryTextSubmit(String query) {
+                // return true to prevent the query is processed to be queried;
```
[the remark this answers is not in the document]
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/c3209d817d8dccc8cc1c5c913658893e34f4ad52

File: src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java (hunk 13 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/c3209d817d8dccc8cc1c5c913658893e34f4ad52

File: src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java (hunk 12 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/c3209d817d8dccc8cc1c5c913658893e34f4ad52

File: src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java (hunk 11 above)
Comment (AndyScherzinger) [reply src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java]: DONE via https://github.com/nextcloud/android/pull/2573/commits/c3209d817d8dccc8cc1c5c913658893e34f4ad52

**Comment by mario** [comment]
👍 

Decent enough :P

**Comment by jancborchardt** [comment]
Yay, awesome work! :) Really looking forward to this landing in the release!
