### PR TITLE
Fix app crashes if local folder is null

### LINKED ISSUE #14845: NullPointerException in RefreshFolderOperation When Internet Connection is too slow
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

The app crashes with a NullPointerException when attempting to invoke setLastSyncDateForData on a null OCFile object during a folder refresh operation. It's only happening when internet connection is too slow.

### Expected behaviour

The app should handle missing or null OCFile instances gracefully without crashing.

### Actual behaviour

The app crashes with a fatal exception due to a NullPointerException.

### Android version

15

### Device brand and model

Android Emulator

### Stock or custom OS?

Stock

### Nextcloud android app version

3.31.0

### Nextcloud server version

31.0.0

### Using a reverse proxy?

I don't know

### Android logs

```
FATAL EXCEPTION: Thread-140
Process: com.nextcloud.client, PID: 19406

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.owncloud.android.datamodel.OCFile.setLastSyncDateForData(long)' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:258)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:387)
    at java.lang.Thread.run(Thread.java:1012)

```

### Server error logs

```bash

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fran-tor**
- [x] Tests written, or not needed

This PR fixes #14845 by handling the mLocalFolder state to avoid the application crashes when it tries to perform the refresh folder operation on a low internet speed connection.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Hi,
and welcome to Nextcloud.
I am very happy that you contribute to our project.

From looking at the code, I currently fail to understand why mLocalFolder can be null, when internet connection is slow.
Can you point me to the way how this can happen?

File: app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java [hunk 1]
```diff
@@ -255,21 +260,26 @@ protected RemoteOperationResult run(OwnCloudClient client) {
...
         }
 
         checkFolderConflictData(result);
 
-        if (!mSyncFullAccount && mRemoteFolderChanged) {
+        if (!mSyncFullAccount && mRemoteFolderChanged && mLocalFolder != null) {
             sendLocalBroadcast(EVENT_SINGLE_FOLDER_CONTENTS_SYNCED, mLocalFolder.getRemotePath(), result);
         }
 
         if (result.isSuccess() && !mSyncFullAccount && !mOnlyFileMetadata) {
```
Comment (tobiasKaminsky) [inline app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java]:
```suggestion
        if (result.isSuccess() && !mSyncFullAccount && !mOnlyFileMetadata && mLocalFolder != null) {
```

**Review by tobiasKaminsky — APPROVED** [review]
