### PR TITLE
Fix npe on version checking

### LINKED ISSUE #3004: [3.3.0 RC2] NPE in FileDisplayActivity.checkOutdatedServer
GPlay
```
Caused by: java.lang.NullPointerException: 
  at com.owncloud.android.ui.activity.FileDisplayActivity.checkOutdatedServer (FileDisplayActivity.java:369)
  at com.owncloud.android.ui.activity.FileDisplayActivity.onPostCreate (FileDisplayActivity.java:304)
  at android.app.Instrumentation.callActivityOnPostCreate (Instrumentation.java:1285)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2760)
```

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #3004 

We could also use capabilities if version is null?

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: 

> We could also use capabilities if version is null?

Don't know, not an expert on the capabilities API

**Comment by tobiasKaminsky** [comment]
If server version is null, it now also tries to parse the capabilites.

File: src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java [hunk 1]
```diff
@@ -365,6 +368,12 @@ private void checkOutdatedServer() {
 
             if (MainApp.getVersionCode() > lastSeenVersion) {
                 OwnCloudVersion serverVersion = AccountUtils.getServerVersionForAccount(account, this);
+                
+                if (serverVersion == null) {
+                    OCCapability capability = getCapabilities();
+                    serverVersion = new OwnCloudVersion(capability.getVersionMayor() + VERSION_DOT +
+                            capability.getVersionMinor() + VERSION_DOT + capability.getVersionMinor());
```
Comment (AndyScherzinger) [inline src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java]: This seems wrong, `Mayor.Minor.Minor`?

Comment (tobiasKaminsky) [reply src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java]: Thanks for the hint :+1:

**Comment by AndyScherzinger** [comment]
:+1: rereviewed: All fine :+1:

**Comment by AndyScherzinger** [comment]
merged, will now create the backport...
